### PR TITLE
Add GFDL variants for invariants and no-invariants

### LINKED ISSUE #686: GNU Free Document Licence with no Invariant Sections
Several old documentation files were written using GFDL licence, with was, on that time, believed to be a free license. However, a more modern read of the license considers it non-free, if an optional "Invariant Sections" part of the license is used. As a reference, see: https://www.debian.org/vote/2006/vote_001

Currently, at https://spdx.org/licenses/, it is only possible to state that a document follows FDL (for example, using SPDX identifier GFDL-1.1-or-later), but currently ther's no way to distinguish between a GFDL with Invariant Sections from a GFDL without it. As explained at: https://spdx.org/licenses/GFDL-1.1-or-later.html ADDENDUM, the files licensed under GFDL that doesn't use Invariant Sections should follow this rule:

	'If you have no Invariant Sections, write "with no Invariant 
	 Sections" instead of saying which ones are invariant. If you
	 have no Front-Cover Texts, write "no Front-Cover Texts"
	 instead of "Front-Cover Texts being LIST"; likewise for
	 Back-Cover Texts.'

So, IMHO, in order to be able to use SPDX without those optional parts of the spec, specially the Invariant Sections, an exception is needed. e. g. something like:

	'Permission is granted to copy, distribute and/or modify this document under
	 the terms of the GNU Free Documentation License; with no Invariant Sections,
	 no Front-Cover Texts and no Back-Cover Texts.'

### PR DESCRIPTION
**Pull request by swinslow**
This adds identifiers for the "-invariants" and "-no-invariants" versions of all of the GFDL licenses. It includes notes for each one explaining when they should be used.

It also cleans up and makes consistent the standard license headers for each version.

Fixes #686

Signed-off-by: Steve Winslow <steve@swinslow.net>

### CODE REVIEW

**Comment by swinslow** [comment]
Discussed on 2020-06-18 legal team call, @MarkAtwood will take a second look at this PR (thank you Mark!)

**Comment by kestewart** [comment]
Why is this not being handled via an exception?    I would think that "WITH no-invariants" would be more appropriate.

**Comment by swinslow** [comment]
@kestewart The format for the identifier here was based on the format from the requester at https://github.com/spdx/license-list-XML/issues/970#issuecomment-644578369 and https://github.com/spdx/license-list-XML/issues/686#issuecomment-644581190 (though I did pluralize it in this PR). I had thought also having the "-only" or "-or-later" immediately following the version number was clearer, so that it was more apparent what that phrase was referring to.

(Regarding not using WITH, this was considered -- discussed on calls last year (https://github.com/spdx/license-list-XML/issues/686#issuecomment-457289896) and one of the options mentioned in #970 (see item 3 on the list there), discussed on the legal team call and decided that because not all of the options are "exceptions" that it wouldn't work to add them as exceptions for use with the WITH operator.)

But I don't have a strong preference on the ordering of the sub-parts here. @mchehab given @kestewart's comment above, are you okay with me switching the identifier order so that it would be e.g. `GFDL-1.2-no-invariants-or-later` instead?

**Comment by mchehab** [comment]
> @kestewart The format for the identifier here was based on the format from the requester at [#970 (comment)](https://github.com/spdx/license-list-XML/issues/970#issuecomment-644578369) and [#686 (comment)](https://github.com/spdx/license-list-XML/issues/686#issuecomment-644581190) (though I did pluralize it in this PR). I had thought also having the "-only" or "-or-later" immediately following the version number was clearer, so that it was more apparent what that phrase was referring to.
> 
> (Regarding not using WITH, this was considered -- discussed on calls last year ([#686 (comment)](https://github.com/spdx/license-list-XML/issues/686#issuecomment-457289896)) and one of the options mentioned in #970 (see item 3 on the list there), discussed on the legal team call and decided that because not all of the options are "exceptions" that it wouldn't work to add them as exceptions for use with the WITH operator.)
> 
> But I don't have a strong preference on the ordering of the sub-parts here. @mchehab given @kestewart's comment above, are you okay with me switching the identifier order so that it would be e.g. `GFDL-1.2-no-invariants-or-later` instead?

Yeah, `GFDL-1.2-no-invariants-or-later` works for me.

**Comment by swinslow** [comment]
Great, thanks @mchehab and @kestewart. I'll rework the PR to switch the identifiers.

**Comment by swinslow** [comment]
@kestewart PR update is done, see 258e461 -- grateful if you can re-review when you have a chance, then I'll merge this.

**Comment by swinslow** [comment]
Discussed on 2020-07-02 legal team call, agreed to merge.

**Pull request merged**
