### PR TITLE
FAQ heading improvements

### PR DESCRIPTION
**Pull request by Jayman2000**
See the individual commit messages for details.

### CODE REVIEW

**Comment by jlovejoy** [comment]
interesting @Jayman2000 - we are not (currently) generating webpages from these .md pages, but... not sure if we might in the future, in which case this would be helpful

@seabass-labrax - thoughts on this?

**Comment by Jayman2000** [comment]
> we are not (currently) generating webpages from these .md pages

GitHub automatically turns Markdown into Web pages for you. If you go [here](https://github.com/spdx/license-list-XML/blob/main/DOCS/faq.md) and inspect the page, you’ll be able to see that the “The SPDX License List” heading is an &lt;h1&gt; and that the “What is the SPDX License List?” heading is also an &lt;h1&gt;.

**Review by seabass-labrax — APPROVED** [review]

**Comment by seabass-labrax** [comment]
Thanks, @Jayman2000! This looks good to me.

For those reading this who might not be aware, a line of equals signs underneath text actually makes that text an 'h1' heading, so this would be two 'h1' headings:

```
> The SPDX License List
> =====================
> 
> # What is the SPDX License List?
```

I would suggest changing that first heading to be written with the more typical hash mark method to prevent future confusion, either in this PR or a follow-up one.

**Comment by Jayman2000** [comment]
> I would suggest changing that first heading to be written with the more typical hash mark method to prevent future confusion, either in this PR or a follow-up one.

OK, I just pushed a new commit to this PR that does that.

**Comment by seabass-labrax** [comment]
Brilliant; thank you!

**Review by seabass-labrax — APPROVED** [review]

**Pull request merged**
