### PR TITLE
New License: BSD-3-Clause-HP

### LINKED ISSUE #2053: New license request: BSD-3-Clause-HP [SPDX-Online-Tools]
**1.** License Name: Hewlett-Packard BSD variant license
**2.** Short identifier: BSD-3-Clause-HP
**3.** License Author or steward: HP
**4.** Comments: It is BSD-3-Clause license with several changes by HP and the changes does not break open source principles. Found during license review in Fedora - https://gitlab.com/fedora/legal/fedora-license-data/-/issues/267 .

The license in COPYING file is without 'All rights reserved', but the source and header files have it, so I've copied the text from the source instead of from COPYING.
**5.** License Request Url: http://tools.spdx.org/app/license_requests/260
**6.** URL(s): 
**7.** OSI Status: Unknown
**8.** Example Projects: 
**8.** License Text Diff: https://github.com/spdx/licenseRequestImages/blob/master/77422b01-ae9b-4a52-a76d-8680ede4127f.png

**Note:**
The license closely matched with the following license ID(s): BSD-3-Clause

### PR DESCRIPTION
**Pull request by jlovejoy**
fixes #2053

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by jlovejoy** [comment]
@swinslow  - can you review and merge?

**Comment by jlovejoy** [comment]
@swinslow - I cannot for the life of me figure out why this is failing... help!

**Comment by swinslow** [comment]
@jlovejoy Missing word in clause 3: "Neither the name of **the** HP . . ." -- weird but that's what's in the original. 

Fixed in c1b9bb0 and will merge after tests pass.

**Comment by jlovejoy** [comment]
thanks @swinslow !

**Pull request merged**
