### PR TITLE
Polyform 1.0.0 Licenses

### PR DESCRIPTION
**Pull request by kemitchell**
This pull request includes the recently recent 1.0.0 source-available licenses from [Polyform Project](https://polyformproject.org): Noncommercial, Strict, Small Business, Internal Use, and Free Trial.

Like BlueOak-1.0.0, Polyform licenses are published in Markdown markup. Those who prefer to peruse rendered HTML can visit https://polyformproject.org/licenses/.

cc @heathermeeker @tieguy

### CODE REVIEW

**Comment by kemitchell** [comment]
Rebased to use the column-wrapped versions as tests for all licenses.

**Comment by kemitchell** [comment]
CI is green. #904 helped a lot!

**Comment by kemitchell** [comment]
Should I plan to attend tomorrow's legal team call if possible?

**Comment by jlovejoy** [comment]
I think it'd be best to hold on these until we complete the license inclusion principles update work. (Admittedly, under the current guidelines, these licenses would probably not be accepted, but given the conversations on changes to the inclusion principles, this may change)

**Comment by rkarthik007** [comment]
Wanted to leave a comment here saying that [Yugabyte](https://github.com/yugabyte/yugabyte-db#license) currently uses Polyform licenses for the Platform product. Our rationale behind adopting this was as follows: while our database product (YugabyteDB) is 100% open-source, our commercial Yugabyte Platform product is source-available. We wanted to pick a standard license rather than craft our own license which becomes confusing for our users.

There is a need for such a standardization across the board, otherwise figuring out the nuances of each vendor's license becomes onerous.

**Comment by kemitchell** [comment]
@heathermeeker, should the SPDX IDs for the licenses be `PolyForm-*` instead of `Polyform-*`?

**Comment by kemitchell** [comment]
Per #885, this PR is being split so that -Noncommercial and -Small-Business can land, with the rest still pending.

**Pull request closed without merging**
