### PR TITLE
Add SHL-0.51

### PR DESCRIPTION
**Pull request by kemitchell**
Ref: #827

### CODE REVIEW

**Comment by kemitchell** [comment]
I did not see an official plain-text rendering on solderpad.org, so I copied the text content of the page and did a little tweaking by hand to get the subsection numbering within Redistribution. Apache uses `(lower-alpha)` for subsections, but SHL uses `arabic` again.

**Comment by kemitchell** [comment]
Probably want to squash-merge this one.

**Comment by jlovejoy** [comment]
pushing this out for 3.6 as it looks like SHL may be used already for short form and need to confer with license author

**Comment by jlovejoy** [comment]
reached out to Andrew Katz, license author re: short identifier and updated file names as per his input (to use SHL)

**Pull request merged**
