### PR TITLE
Update xml-fields.md

### LINKED ISSUE #2584: XML explanation re: use of ? in markup
Add another example of using `?` in a string to the existing example ("express(ed)") that is more complex, e.g. BSD-3-Clause and "specific" in #2529 

question mark applies to thing immediately before it, which could be a comma also 

(compare to optional tag - note can't have optional tag within alt tag)

### PR DESCRIPTION
**Pull request by jlovejoy**
fixes #2584 

need some input on a few things - see comments below

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by jlovejoy** [comment]
@goneall @swinslow - this mentions `<obsoletedBys>` - but are we not using that any more? If so, should we remove here?

**Comment by jlovejoy** [comment]
@swinslow can you check my explanation of `?` - especially in regard to the "specific" example :)

**Review by swinslow — APPROVED** [review]
LGTM, thanks @jlovejoy!

**Comment by swinslow** [comment]
And `obsoletedBy` is still in the spec and some of the licenses, so I would keep it in the docs for now.

**Pull request merged**
