### PR TITLE
Unlicense "For more information..." line is optional

### PR DESCRIPTION
**Pull request by mlinksva**
See https://unlicense.org which says:

> You should feel free, though, to leave out the last line containing the link to this site, if that's your preference.

As pointed out by @Hexstream at https://github.com/unlicense/unlicense.org/pull/55#issuecomment-420831489 (and more recently).

### CODE REVIEW

**Comment by Hexstream** [comment]
Thank you for moving this forward!

The link in the last line of the Unlicense should also be updated to HTTPS in the template, as has already been done in the [website repo](https://github.com/unlicense/unlicense.org/commit/2ada423674f0f87af7239b852e74a12d97d74945) but has somehow not yet been reflected in the [live site](https://unlicense.org/).

**Comment by Hexstream** [comment]
That was quick! :zap:

**Comment by mlinksva** [comment]
Makes sense to me. http->https has been done for various other licenses where the license stewards have updated their copies, and most license matching tools normalize.

**Comment by mlinksva** [comment]
Whoops, I failed to mention that I had opened this where I had suggested the need for it most recently, resulting in #918. Closing this in preference to that one.

**Pull request closed without merging**
