### PR TITLE
New License: Unicode-3.0

### LINKED ISSUE #2105: New license request: Unicode-3 [SPDX-Online-Tools]
**1.** License Name: Unicode License v3
**2.** Short identifier: Unicode-3
**3.** License Author or steward: Unknown
**4.** Comments: The license is presented in pypi package. Found during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/314
**5.** License Request Url: http://tools.spdx.org/app/license_requests/283
**6.** URL(s): https://www.unicode.org/license.txt
**7.** OSI Status: Pending
**8.** Example Projects: https://www.unicode.org

### PR DESCRIPTION
**Pull request by jlovejoy**
Fixes #2105

hold for official OSI approval

Still needs version number added

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by swinslow** [comment]
@jlovejoy Given your comment at https://github.com/spdx/license-list-XML/issues/2105#issuecomment-1742141902 I think you want to hold off on merging this for now? Assuming that's the case, I'm switching it to Draft mode.

**Comment by xsuchy** [comment]
The linked issue made some progress. Do you think we can proceed here? I would start by removing the draft label.

**Comment by jlovejoy** [comment]
now officially added to OSI

**Review by swinslow — COMMENTED** [review]
Reviewing after the fact, but LGTM

**Pull request merged**
