### PR TITLE
AGPL 1.0 is FSF approved

### PR DESCRIPTION
**Pull request by Tyler887**
https://gnu.org/licenses/license-list.en.html#AGPLv1.0

### CODE REVIEW

**Comment by goneall** [comment]
AGPL 1.0 is listed a GPL incompatible on the [FSF website](https://www.gnu.org/licenses/license-list.en.html#GPLIncompatibleLicenses).

The same site does not mention if 1.0 is approved or not.

BTW - the FSF free flags are automatically added through the FSF-API when the license list is published.  So if we decide this is approved, we need to update the [FSF-API code](https://github.com/spdx/fsf-api) to add a [tag override](https://github.com/spdx/fsf-api/blob/145522eb72f51922b68fc5cd5064b90325036639/pull.py#L91) for this license.

**Comment by seabass-labrax** [comment]
The AGPL 1.0 is indeed considered free by the FSF; their license page (on gnu.org) has it under 'GPL-Incompatible Free Software Licenses', which confusingly (at least in my opinion) is next to a dashed orange line.

**Comment by seabass-labrax** [comment]
I've made pull request https://github.com/spdx/fsf-api/pull/22 to fix this.

**Comment by seabass-labrax** [comment]
This issue has been resolved in pull request https://github.com/spdx/fsf-api/pull/22 - it'll be listed as FSF Free/Libre in the next SPDX License List release!

**Comment by swinslow** [comment]
Great, thanks @seabass-labrax and everyone!

**Pull request closed without merging**
