### PR TITLE
Update LicenseListPublisher to version 2.2.5

### PR DESCRIPTION
**Pull request by goneall**
Very minor update to the LicenseListPublisher.  Primary change is
to update the log4j version to 2.17.0.  Previous version of log4j
has know security vulnerabilities.

Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

### CODE REVIEW

**Comment by goneall** [comment]
The CI push is failing when downloading the Java version.  This is before the download or execution of the LicenseListPublisher and likely unrelated to the changes in this PR.  Note that the Validate canonical match (pull_request) executes the same code and was successful.

There was a previous attempt at passing the CI with Java version 11.  It also failed in the Validate canonical match (push) hanging on the utility execution before any licenses were compared.

We can try to run the CI again later and see if it clears up.

**Comment by goneall** [comment]
CI worked when restarted today.

Changing Java version back to 11 to see if the problem goes away for that version as well.

**Comment by goneall** [comment]
The CI looks like it is running fine now.

Must have been some glitch in the CI infrastructure.

This should be ready to merge.

**Comment by goneall** [comment]
@swinslow Could you just do a quick look at the PR and merge if you don't see any issues?

**Comment by swinslow** [comment]
LGTM, thanks @goneall! Merging now.

**Pull request merged**
