### PR TITLE
update clause 3 to original text

### PR DESCRIPTION
**Pull request by jlovejoy**
update clause 3 to match original text at http://www.apache.org/licenses/LICENSE-1.0 and add period at end of clause as per https://github.com/spdx/license-list-XML/issues/396

### CODE REVIEW

**Comment by goneall** [comment]
I would remove the spaced in name="nameClause4" match="name | names | name(s)" -> name="nameClause4" match="name|names|name(s)"

Other than that it looks fine

**Comment by goneall** [comment]
@bradleeedmondson @jlovejoy I just realized there is one more fix needed - the parenthesis are special characters and need to be escaped with a "\".  match="name | names | name(s)" -> match="name|names|name\(s\)"  I looked at the most recent patch and the name pattern is no longer in the file - so I don't think anything further needs to be done.

**Comment by bradleeedmondson** [comment]
No it's still there on line 41:
https://github.com/spdx/license-list-XML/blob/master/src/Apache-1.1.xml#L41

I'm not sure the escape character you intended came through in the comment (it may need to be escaped as well?). I'm assuming it's a backslash \ but let me know if that's wrong.

**Comment by bradleeedmondson** [comment]
escaped parens with backslash in f1636ca7e60dbc4c79ba34e8d4014c97185f48df

**Comment by goneall** [comment]
@bradleeedmondson The backslashes were removed in the comment - I did check your commit f1636ca and it looks correct

**Comment by wking** [comment]
The branch from this PR (`jlovejoy-patch-1`) is still in this repo.  Can someone with write access remove it now that it's no longer needed?  And `jlovejoy-patch-2` from #401 is in the same boat.

**Comment by bradleeedmondson** [comment]
removed

**Pull request merged**
