### PR TITLE
New License: Graphics-Gems

### LINKED ISSUE #1552: New license request: Graphics-Gems [SPDX-Online-Tools]
**1.** License Name: Graphics Gems EULA
**2.** Short identifier: Graphics-Gems
**3.** License Author or steward: Eric Haines
**4.** Comments: The license is found in at least one Fedora package and undoubtedly is present in counterpart packages in other Linux distributions. While horribly worded, in my view the license meets criterion 1 (hence it is likely to be classified as 'allowed' by Fedora).
**5.** Standard License Header: 
**6.** License Request Url: http://tools.spdx.org/app/license_requests/150
**7.** URL(s): http://www.realtimerendering.com/resources/GraphicsGems/, https://github.com/erich666/GraphicsGems/blob/master/LICENSE.md
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://webkitgtk.org/

### PR DESCRIPTION
**Pull request by jlovejoy**
fixes #1552 

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by jlovejoy** [comment]
OMG! @swinslow @goneall - I submitted a PR and it passed tests on the FIRST TRY!!!

**Comment by jlovejoy** [comment]
nevermind... I added another license file here instead of a new branch, deleted it, and now it's failing..

**Comment by swinslow** [comment]
@jlovejoy Haha -- so close  :)  I might be able to remove the two extra commits from this PR, one moment...

**Comment by swinslow** [comment]
🎉

**Pull request merged**
