### PR TITLE
New License: Minpack

### PR DESCRIPTION
**Pull request by jlovejoy**
files for Minpack

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by jlovejoy** [comment]
fixes #1522

**Review by swinslow — APPROVED** [review]
LGTM  👍

**Comment by swinslow** [comment]
Already approved to add Minpack in #1522. I'll let this PR sit for a couple of days in case anyone else has +1's or sees any issues, will merge otherwise.

**Review by Luis123QG — APPROVED** [review]

**Review by Luis123QG — APPROVED** [review]
jlovejoy-patch-1

**Comment by swinslow** [comment]
Merged!

**Pull request merged**
