### PR TITLE
Use relative Markdown links for stuff stored in this repo

### PR DESCRIPTION
**Pull request by Jayman2000**
See the individual commit messages for details.

### CODE REVIEW

**Comment by jlovejoy** [comment]
thanks for the cleanup, @Jayman2000 !

**Comment by jlovejoy** [comment]
hmmm... I think I updated this file since you made this PR and now there are conflicts... not sure how to resolve those...

**Comment by Jayman2000** [comment]
> hmmm... I think I updated this file since you made this PR and now there are conflicts... not sure how to resolve those...

I just pushed a new version that was rebased on the main branch.

**Comment by jlovejoy** [comment]
Thanks!

**Pull request merged**
