### PR TITLE
Add github issue template for new license

### PR DESCRIPTION
**Pull request by oliverpool**
_Suggestion following my first contribution to this project (#1735):_

I found the guidelines regarding how to add a request quite understandable.

To make them even more accessible, I propose to add a [github issue template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository) for `New license requests` (like https://tools.spdx.org/app/submit_new_license/)

Here is what I came up with:
- The `New license request` is a form with required fields and links to documentation- [try it on my fork](https://github.com/oliverpool/license-list-XML/issues/new?assignees=&labels=new+license%2Fexception+request&template=new-license-request.yaml&title=New+license+request%3A+)
- upon creation, the `new license/exception request` label is automatically added

Example on my fork: https://github.com/oliverpool/license-list-XML/issues/3

### CODE REVIEW

**Comment by jlovejoy** [comment]
Thanks @oliverpool - do I understand that this is basically intended to mirror the online tool and be an alternative way to submit a new license request directly in Github, instead of via the online tool?

**Comment by oliverpool** [comment]
Yes, exactly (this way the user does not need to grant some access to the spdx application on github)

**Comment by jlovejoy** [comment]
so, now that I've processed some record number of license requests for the 3.20 release, here is my one big hesitation for having this:
- when someone submits a license via the online tool, it means that once that license is accepted to add to the list, someone can also use the online tool to generate the XML file. This makes that work MUCH easier than creating the XML file manually (for most of us). I actually re-submitted a license via the online tool to be able to leverage this functionality.
- If someone submits via an issue instead of the online tool, that means the XML editor can't be used (as easily). 

If we could guarantee that submitters would help create the files if the license is accepted, then I'd be okay with offering this alternative way to submit, but we haven't been so successful in getting that help :(

**Comment by oliverpool** [comment]
> when someone submits a license via the online tool, it means that once that license is accepted to add to the list, someone can also use the online tool to generate the XML file

I didn't know about that. I guess you are referring to the page https://tools.spdx.org/app/license_requests/? Maybe a link to this page could be added to https://github.com/spdx/license-list-XML/blob/main/DOCS/new-license-workflow.md (under [New License Workflow](https://github.com/spdx/license-list-XML/blob/main/DOCS/new-license-workflow.md#new-license-workflow) > `SPDX online tools page` for instance)

---

I have tried adding a link to the online tool, however it can only appear at the end, which is not ideal: https://github.com/oliverpool/license-list-XML/issues/new/choose

image

([this is a known github limitation](https://github.com/orgs/community/discussions/21601))

---

Feel free to close this issue if you think that this solution is not ideal (I just contributed to one license, so you are in the best position to judge if such templates would be useful).

**Review by swinslow — APPROVED** [review]

**Review by seabass-labrax — APPROVED** [review]

**Comment by swinslow** [comment]
Discussed on legal team call 2023-02-23, agreed to merge.

**Pull request merged**
