### PR TITLE
Automated PR for YPL-1.1

### PR DESCRIPTION
**Pull request by myndzi**

### CODE REVIEW

**Comment by bradleeedmondson** [comment]
What's the question for legal discussion here?

**Comment by jlovejoy** [comment]
I don't think we need the optional tag at the top

**Comment by bradleeedmondson** [comment]
agree, since this is a vanity license there's no reason to mark that paragraph as optional

**Comment by pmadick** [comment]
Agreed.  Remove optional mark and commit.

**Pull request merged**
