### PR TITLE
Add release notes for 3.26.0

### LINKED ISSUE #2619: 3.26.0 Pre-release notes
Things to verify before release (add to list as needed):

* [x] Double-check `listVersionAdded` 3.26 => 3.26.0
* [ ] Manually set link to matching guidelines to https://spdx.github.io/spdx-spec/v3.0.1/annexes/license-matching-guidelines-and-templates/ before uploading (see https://github.com/spdx/LicenseListPublisher/issues/186)
* [x] Add release notes

### PR DESCRIPTION
**Pull request by swinslow**
Fixes #2619

Signed-off-by: Steve Winslow <steve@swinslow.net>

### CODE REVIEW

**Review by blg666 — APPROVED** [review]

**Comment by F5beep** [comment]
اريد ضبط الملف الشخصي

**Review by F5beep — CHANGES_REQUESTED** [review]
طلب مساعده

**Review by Nous5 — APPROVED** [review]

**Comment by Ekene1998** [comment]
/

**Review by Ekene1998 — COMMENTED** [review]
> [!IMPORTANT]
>  _

**Comment by booter2418** [comment]
This copyright goes to: Joseph Thornton Jr.
All rights are reserved unless otherwise licensed.

Commercial use requires a paid license with royalties.

The license was issued in Okeechobee, Florida

**Review by Nous5 — APPROVED** [review]

**Pull request merged**
