### PR TITLE
Add Parity-6.0.0

### PR DESCRIPTION
**Pull request by kemitchell**
This draft PR for #805 gave me another change to make an XML file.

The only interesting bit in this one, I think, is the source line. I vaguely remember another BSD or MIT variant doing something similar, but I'm not sure it was templatized. In any case, I called the placeholder "source".

### CODE REVIEW

**Comment by swinslow** [comment]
@kemitchell If the legal team gives the thumbs-up for including Parity on the list, is this XML file ready to go from your perspective?

If so, and if you want to move it out of "Draft" mode, I assume (without really knowing) that the CI checks will run and we can confirm in parallel whether there's any formatting issues.

**Comment by ghuntley** [comment]
Looking forward to this addition!

**Comment by kemitchell** [comment]
Amending to address some matching issues.

**Comment by kemitchell** [comment]
I was able to get the matching test passing by dropping the `<optional></optional>` around the asterisks that Parity uses to make its warranty disclaimer and damages exclusion conspicuous.

**Comment by swinslow** [comment]
Thanks @kemitchell. If we need to iterate later to clarify and address the asterisks you mentioned, that's the sort of template markup that we can address in subsequent PRs. 

Parity was approved by the Legal Team this morning to add to the list. This PR looks good to me -- @jlovejoy @goneall @bradleeedmondson, would one of you mind just being a second set of eyes to also give this a +1, and then I can merge? Thanks!

**Pull request merged**
