### PR TITLE
Create history.md

### PR DESCRIPTION
**Pull request by jlovejoy**
creating a timeline for the SPDX License List, first commit / rough draft. More work to do here

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by swinslow** [comment]
@jlovejoy I see this is labeled as a "rough draft" -- would you like this to go ahead and be merged now, or is this still a work in progress before merging? LGTM either way.

**Comment by jlovejoy** [comment]
@swinslow - still a work in progress that I need to get back to. Please leave as it's a bit of a mess at this point! I'll ping you for review when it's a bit more polished!

**Comment by jlovejoy** [comment]
@swinslow - I think you can merge this now and we can add stuff as we think of it.

tagging @kestewart @goneall @zvr for awareness (and the trip down memory lane!!!)

**Review by swinslow — APPROVED** [review]
LGTM, thanks @jlovejoy! Merging now.

**Pull request merged**
