### PR TITLE
Add PolyForm-Free-Trial-1.0.0

### PR DESCRIPTION
**Pull request by kemitchell**
Split off from #903
Issue: #885

### CODE REVIEW

**Comment by jlovejoy** [comment]
I added url for text file also and note about purpose of license to @kemitchell PR - ready to merge as far as I'm concerned!

**Comment by jlovejoy** [comment]
ha! just realized these three are the ones we aren't going to add (yet)!  oops! I got backwards on that. will tag accordingly.

**Comment by jlovejoy** [comment]
can we close this and then re-open later if need be? (trying to do some clean-up :)

**Comment by swinslow** [comment]
@jlovejoy agreed, I'll close this and the others, and we can re-open later if need be.

**Pull request closed without merging**
