### PR TITLE
Add UCL-1.0.xml #894

### PR DESCRIPTION
**Pull request by johnmhoran**
* Used OSL-3.0.xml as a template.

Signed-off-by: John M. Horan <johnmhoran@gmail.com>

### CODE REVIEW

**Comment by swinslow** [comment]
This is for issue #894

**Comment by swinslow** [comment]
@johnmhoran I made a couple of tweaks, to add the license list version where this will first be added (3.7) and to make the angle-bracketed text optional.

On the latter point, that's because the instances where we've seen this license used (https://github.com/ftc-team-11553/ftc_2017/blob/master/LICENSE.md and the OSI website), that language has been absent -- but in the [original submission to OSI](http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2017-February/002980.html), it was present. Probably easiest for SPDX purposes to mark that bit as `<optional>` so that either occurrence would match. Does that work for you?

**Comment by johnmhoran** [comment]
Thanks @swinslow .  Very cool that you found Nigel Tzeng's original submission.  From a drafting/interpretation point of view the missing language (or equivalent) seems mandatory, not optional -- but if our primary goal is matching incoming text, `<optional>` seems the way to go.

**Comment by swinslow** [comment]
Discussed on 2019-09-05 call, ready to merge with optional text included; @jlovejoy to flag for OSI

**Pull request merged**
