### PR TITLE
Add equivalent words text file per #927

### LINKED ISSUE #927: Proposal: Add a machine readable form of equivalent words
The license matching guidelines list a number of words which are equivalent in the documentation.  Adding this in a machine readable form in the license-XML repository would allow for tools to pick up the latest and greatest with minimal effort.

### PR DESCRIPTION
**Pull request by swinslow**
Fixes #927

Signed-off-by: Steve Winslow <swinslow@gmail.com>

### CODE REVIEW

**Comment by zvr** [comment]
LGTM

**Comment by goneall** [comment]
Looks good.

Thanks @swinslow

**Comment by jlovejoy** [comment]
should this live in the DOCS directory?

**Comment by goneall** [comment]
To resolve the duplication of information, can we have the matching guidelines doc refer to this file?

**Pull request merged**
