### PR TITLE
new license: BSD-Systemics-W3Works

### PR DESCRIPTION
**Pull request by xsuchy**
Fixes: #2169

### CODE REVIEW

**Comment by xsuchy** [comment]
I believe that the failed check is not because of the content of the PR, but because failed CI script.

**Comment by swinslow** [comment]
Thanks @xsuchy -- very strange. I agree this looks like a script issue. It's saying that [BSD-Systemics](https://spdx.org/licenses/BSD-Systemics.html) is matching this one, though that seems very odd given that this clearly has additional text (as non-optional required text) so it shouldn't be matching.

I'm going to play around with it a bit more to see what's going on. I'm wondering if perhaps it's something to do with the `match=".*"` alt-tags matching more than they're supposed to. I'll take a closer look and will follow up.

**Comment by jlovejoy** [comment]
was there another instance of this license found with a different name? I noticed that @xsuchy put markup around all the names, but we usually don't do that if it's a one-off license (or until we find another example). Not sure if that would mess up the tests?

**Comment by xsuchy** [comment]
It is only one instance. I added there the alts because I got here one thumbs up. https://github.com/spdx/license-list-XML/issues/2169#issuecomment-1770122139

**Comment by jlovejoy** [comment]
> It is only one instance. I added there the alts because I got here one thumbs up. [#2169 (comment)](https://github.com/spdx/license-list-XML/issues/2169#issuecomment-1770122139)

I think that was markup for spelling errors, not names. Just wondering if that in any way was contributing to failing tests.

**Comment by xsuchy** [comment]
> spelling errors, not names

??? what names? I thought that I added <alt> for spelling errors only. Do I miss something?

**Comment by jlovejoy** [comment]
well, removing the alt markup around the names worked so I'm merging!

**Pull request merged**
