### PR TITLE
openvpn-openssl-exception - add markup

### PR DESCRIPTION
**Pull request by jlovejoy**
adding markup for variations as per #1356 

there is additional variants to add, but starting with this to make sure I have markup correct!

### CODE REVIEW

**Review by swinslow — APPROVED** [review]

**Comment by swinslow** [comment]
Oh wait -- I approved this, but just saw the failing test. Taking a closer look...

**Comment by goneall** [comment]
> Hmmm... from the failing test, I think it's failing because of the <optional>s</optional> occurring in the middle of a word. I'm not sure if that works.

Yup - that doesn't work.  You could call it a tooling issue, but it would be very very difficult to implement character level optional characters unless they are at the beginning or ending of a token/word.  It may even be impossible to implement such a pattern matcher with a deterministic completion time.  Even at the beginning/end it is very difficult to code for this scenario.

> `<alt name="give" match="give|gives">gives</alt>`

should work as a workaround.

**Comment by jlovejoy** [comment]
thanks @swinslow - yeah, I kind of thought the optional tag was a bit weird there.

made update in my file, but still seeing "change requested" tag - not sure how or if I need to turn that off?

**Comment by jlovejoy** [comment]
hmmm still failing. I think I need to add the optional text to the .txt file too?

**Comment by swinslow** [comment]
Hmmm... for the updated failing test log, it looks like it's this part of the match that is now failing:

`<alt name="thisProgram" match="(the code of this program)|(this program)">the code of this program</alt>`

I'm not sure why this is failing, but I'd note that I think this would be equivalent:

`<optional>the code of</optional> this program`

so maybe that would work better / make the tests pass?

**Comment by goneall** [comment]
I don't see an obvious problem with `<alt name="thisProgram" match="(the code of this program)|(this program)">` the code of this program</alt>`   The parenthesis don't add and value for this regex, so you could try `<alt name="thisProgram" match="the code of this program|this program">`.

If either approach doesn't work, I can bring this into my local debugging environment and find out why it's failing.

**Comment by jlovejoy** [comment]
@goneall was right! it was the parens. Turned out I had another PR I started, so I incremented off that one with each change so I could see what the issue was (will now close this PR)

**Comment by jlovejoy** [comment]
closing in favor of $1436

**Pull request closed without merging**
