### PR TITLE
Make last line of Unlicense optional

### PR DESCRIPTION
**Pull request by corollari**
See discussion in unlicense/unlicense.org#69.

### CODE REVIEW

**Comment by swinslow** [comment]
@corollari Thanks for submitting! I'm in favor of this, but I will add an issue to highlight it so others on the team see it and can weigh in. 

(Some participants on the SPDX legal team look primarily at the Issues list and might miss PRs without issues.)

**Comment by corollari** [comment]
I didn't know of the existence of #916 myself either.

**Comment by jlovejoy** [comment]
this looks good to go to me!

**Comment by corollari** [comment]
Added the changes that were done in #916, both PRs are literally the same (I just opened this one because I didn't properly check the PR log), so any one of these two could be merged.

**Comment by swinslow** [comment]
Merged now, thank you @corollari!

**Pull request merged**
