### PR TITLE
New exception: SHL-2.1

### PR DESCRIPTION
**Pull request by jlovejoy**
xml file for SHL-2.1

### CODE REVIEW

**Comment by jlovejoy** [comment]
hmmm, thought I add .txt file to PR, but not seeing it...

**Comment by jlovejoy** [comment]
both files there now, but still failing - sigh

**Comment by swinslow** [comment]
I'm on calls for next couple of hours, but I'll take a look  :)  Thanks for getting these going!

**Comment by jlovejoy** [comment]
@swinslow - it seems to think there's no .txt file and its looking in the exceptions folder - but we've added other exceptions and passed tests?
@goneall might have an insight

**Comment by swinslow** [comment]
looking at the test log, in lines 222 and 223 it looks like it's having issues with parsing the XML file as invalid:

>Processing License List19:32:45.022 [main] ERROR org.spdx.licensexml.LicenseXmlDocument - Invalid license XML file SHL-2.1.xml
>org.xml.sax.SAXParseException: cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://www.spdx.org/license":standardLicenseHeader}'. One of '{"http://www.spdx.org/license":p, "http://www.spdx.org/license":bullet, "http://www.spdx.org/license":list, "http://www.spdx.org/license":optional, "http://www.spdx.org/license":alt, "http://www.spdx.org/license":br, "http://www.spdx.org/license":titleText, "http://www.spdx.org/license":copyrightText}' is expected.

I'm taking a closer look, will see if I can tell why it might be failing...

**Comment by swinslow** [comment]
Ah, I think it might be because the `<standardLicenseHeader>` section is appearing within the `<text>` section. Looking at another example I think it might need to be outside. I'm jumping on another call but will experiment afterwards to see if that fixes it...

**Comment by jlovejoy** [comment]
> Ah, I think it might be because the `<standardLicenseHeader>` section is appearing within the `<text>` section. Looking at another example I think it might need to be outside.

I don't think it's that, as I have it the same way as in Apache-2.0

**Comment by zvr** [comment]
@jlovejoy @swinslow the two `</br>` in lines 38 and 39 should probably be `<br/>`  :wink:

**Comment by swinslow** [comment]
I just pushed another commit which should fix it (at least it's working on the test on my local machine) -- two changes:
* fixed the br tags -- actually just removed and replaced them with p tags
* removed the standardLicenseHeader tags

My best guess is that there's something about using standardLicenseHeader in an exception that is causing it to break. From a quick search it doesn't look like any of the other exceptions use this tag. Will wait to confirm that it passes...

Note also that I gather there have been some updates to the upstream text (per discussion in #1027) so we should make sure to capture those too before merging.

**Comment by swinslow** [comment]
Good to go now. @andrewjskatz, could you take a look at https://raw.githubusercontent.com/spdx/license-list-XML/d2397ad0e0dac0c225bceccd65833705853cd3ec/test/simpleTestForGenerator/SHL-2.1.txt and confirm that you are good with locking it in as the 2.1 text?

**Comment by andrewjskatz** [comment]
Looks great - thanks Steve!

Andrew Katz
+44 7970 835001
I'm emailing from my smartphone, so please excuse terseness!

**Comment by swinslow** [comment]
Looks like we're good to go -- I'm merging this. Thank you @jlovejoy @andrewjskatz @zvr!

**Pull request merged**
