### PR TITLE
New License: fwlw

### LINKED ISSUE #2086: New license request: fwlw (was: texlive-Arseneau-1993) [SPDX-Online-Tools]
**1.** License Name: texlive Arseneau 1993 License
**2.** Short identifier: texlive-Arseneau-1993
**3.** License Author or steward: Donald Arseneau
**4.** Comments: This license has been found in texlive-fwlw during Fedora license review https://gitlab.com/fedora/legal/fedora-license-data/-/issues/294
**5.** License Request Url: http://tools.spdx.org/app/license_requests/276
**6.** URL(s): https://mirrors.nic.cz/tex-archive/macros/latex/contrib/fwlw/README
**7.** OSI Status: Unknown
**8.** Example Projects: https://tug.org/texlive/cd /

### PR DESCRIPTION
**Pull request by jlovejoy**
Fixes #2086

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by jlovejoy** [comment]
need to update to add Note

**Comment by swinslow** [comment]
Based on our conversation on the 2023-09-14 legal team call, I think we're separating these out...

**Comment by jlovejoy** [comment]
@swinslow ready to merge

**Comment by jlovejoy** [comment]
NOW it's ready to merge @swinslow

**Review by swinslow — APPROVED** [review]

**Pull request merged**
