### PR TITLE
New License: MIT-Khronos-old

### LINKED ISSUE #2017: New license request: MIT-Khronos [SPDX-Online-Tools]
**1.** License Name: MIT Khronos Variant
**2.** Short identifier: MIT-Khronos
**3.** License Author or steward: Khronos Group
**4.** Comments: It appears to be a variant of the MIT license. The licensecheck tool reports it as a separate license called "Khronos license." Here is the Fedora license review discussion, in which it was approved for Fedora: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/238
**5.** License Request Url: http://tools.spdx.org/app/license_requests/240
**6.** URL(s): https://github.com/KhronosGroup/SPIRV-Cross/blob/main/LICENSES/LicenseRef-KhronosFreeUse.txt
**7.** OSI Status: Not Submitted
**8.** Example Projects: https://github.com/KhronosGroup/glslang, https://github.com/KhronosGroup/SPIRV-Cross

### PR DESCRIPTION
**Pull request by jlovejoy**
Fixes #2017

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by jlovejoy** [comment]
Hold til Feb 10 for last input from Khronos Group before merging

**Review by xsuchy — APPROVED** [review]
LGTM

**Comment by jlovejoy** [comment]
@swinslow - I think we can go ahead and merge this now

**Comment by swinslow** [comment]
Thanks @jlovejoy! I just submitted 84685e8 with two tweaks, one to update the listVersionAdded to 3.24 and the other to fix the filename. For some reason it had an `-exception` suffix at the end of the XML filename. After the tests pass (and assuming they do), I'll merge this.

**Pull request merged**
