### PR TITLE
Switch from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by iamwillbar**
@goneall can we co-ordinate when you merge this so I can be available to help debug any issues?

### CODE REVIEW

**Comment by goneall** [comment]
@iamwillbar Thanks for pulling this together!  

I'll coordinate on today's call or later via email as to when to merge.

**Review by goneall — APPROVED** [review]

**Comment by swinslow** [comment]
You rock -- thank you both  :)  I won't merge this, will leave it to @goneall to merge once you both are ready.

cc @jlovejoy just for visibility

**Comment by goneall** [comment]
@iamwillbar Let me know if your free this afternoon, Friday or Monday to test out the deployment

**Comment by goneall** [comment]
@iamwillbar Ended up failing with the following message:

```
git -C '.tmp' add -A .
git -C '.tmp' commit --author "License Publisher (maintained by Gary O'Neall) <gary@sourceauditor.com>" -m "License list build 2f5c720 using license list publisher 2.1.23"
Committer identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
Makefile:23: recipe for target 'deploy-license-data' failed
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <runner@fv-az60-303.osflnz5hn5cepl355w42jubhgh.cx.internal.cloudapp.net>) not allowed
make: *** [deploy-license-data] Error 128
Error: Process completed with exit code 2.
```

**Comment by iamwillbar** [comment]
@goneall easily fixed, should I used the author name and email you have in the commit `"License Publisher (maintained by Gary O'Neall) <gary@sourceauditor.com>"` or is there a generic one we can use?

**Comment by goneall** [comment]
@iamwillbar It would be nice to have a generic committer like licenseListPublisherBOT, but since we don't have one setup, we can continue using the same author and email.

**Comment by iamwillbar** [comment]
@goneall hopefully this will fix it: https://github.com/spdx/license-list-XML/pull/1192. I'm still around to keep an eye on things.

**Comment by goneall** [comment]
@iamwillbar 

Looks like this fixed the issue - running into the following:

```
 [master 39a067d] License list build 5019752 using license list publisher 2.1.23
 4238 files changed, 33338 insertions(+), 33302 deletions(-)
git -C '.tmp' push origin
fatal: could not read Password for 'https://***@github.com': No such device or address
make: *** [deploy-license-data] Error 128
Makefile:23: recipe for target 'deploy-license-data' failed
```

Let me know if I need to make any configuration changes.

**Pull request merged**
