### PR TITLE
Add CC-BY-3.0-AU

### PR DESCRIPTION
**Pull request by NCI-datacollections**
Adding approved new variant licence (CC-BY-3.0-AU) as per issue #2042 (https://github.com/spdx/license-list-XML/issues/2042).

### CODE REVIEW

**Comment by jlovejoy** [comment]
Thanks @NCI-datacollections !

@swinslow - have we been using the "obsoletedBy" tag on these? I think it might be the first time I've seen it used?!

**Comment by NCI-datacollections** [comment]
@jlovejoy - thanks for reviewing this submission. My understanding is that while the CC-BY-3.0-AU license is still used by some government agencies in Australia, many have moved to CC-BY-4.0. Perhaps "obsoletedBy" should be removed in this instance.

**Comment by jlovejoy** [comment]
@NCI-datacollections  I'm wondering if that will solve the tests as well - can you remove the obsoletedBy tags and then I'll re-run tests?

**Comment by NCI-datacollections** [comment]
@jlovejoy Sure thing. I'll amend and resubmit shortly.

**Review by gatleas17 — APPROVED** [review]

**Comment by jlovejoy** [comment]
@swinslow - can you have a look at this? I don't know why it's still failing and it's been hanging around for a bit!

**Comment by swinslow** [comment]
@jlovejoy Looks like the issue was a few instances of extraneous periods being included in the XML file but not in the test text file. I've removed them in 72bea3b, and will wait for tests to re-run to confirm they're good before merging.

**Pull request merged**
