### PR TITLE
Remove the optional https 

### PR DESCRIPTION
**Pull request by goneall**
The SPDX matching tools now support normalizing http and https.

Related to proposal and issue #633 

Signed-off-by: License Publisher(Gary O'Neall) <gary@sourceauditor.com>

### CODE REVIEW

**Comment by goneall** [comment]
Looks like there is still some more work to be done on the tools - I'll work on this over the next couple of days.

**Comment by goneall** [comment]
All issues resolved.

We can merge pending outcome of discussion in issue #633

**Comment by jlovejoy** [comment]
@goneall  can you confirm that we can merge this? (and then need to make a PR to the matching guidelines? but we have some other things to update there and it has its own versioning)

**Comment by goneall** [comment]
@jlovejoy Looks like issue #633 is still open - let's leave this unmerged for now.

**Comment by jlovejoy** [comment]
what is the status of this @goneall

**Comment by goneall** [comment]
@jlovejoy Since issue #633 has been closed so this can now be merged.

I just committed changes to resolve some merge conflicts.

I need to run the verification tests - once completed, I'll go ahead and merge.

**Pull request merged**
