### PR TITLE
src: Whitespace cleanup

### PR DESCRIPTION
**Pull request by wking**
Details in the commit messages, but this PR is about removing unnecessary whitespace from the source.  It keeps helpful whitespace (like indentation) and whitespace that is semantically important (e.g. between words ;).

### CODE REVIEW

**Comment by jlovejoy** [comment]
@goneall  - this looks ok to merge to me, but can you please check?

**Comment by wking** [comment]
Rebased around #406 and #193 with c0f5a64 → f81d96f.

**Comment by wking** [comment]
This is stale again now that #37 has landed and pulled in more whitespace issues.  Instead of continually rebasing, I'll just let this branch go stale.  Let me know when you have time to review, and I'll run a new rebase then.

**Comment by bradleeedmondson** [comment]
Plan is to land all automated PRs so full license list is represented, then do cleanup. @goneall has done cleanup on existing licenses in schemadev branch, so you could check there to make sure whitespace looks good and let him know if you'd go further.

**Comment by wking** [comment]
> Plan is to land all automated PRs...

Loons like there are only ~20 of those in the pipe.  Maybe leave this open and I'll rebase when you're ready for it.

**Comment by goneall** [comment]
@wking @bradleeedmondson I'll let you know when the license list changes settle down and I re-run the conversion on he branch and we're ready to rebase.

**Pull request closed without merging**
