### PR TITLE
Add CC-BY-NC-SA-3.0-IGO

### LINKED ISSUE #1210: New license request: CC-BY-NC-SA-3.0-IGO [SPDX-Online-Tools]
**1.** License Name: Creative Commons Attribution-NonCommercial-ShareAlike 3.0 IGO
**2.** Short identifier: CC-BY-NC-SA-3.0-IGO
**3.** License Author or steward: Creative Commons
**4.** Comments: The omission of this license looks like an oversight.  The CC-BY-NC-ND-3.0-IGO license is currently included, for example.  I have no idea what the OSI Status is but was forced to select "Not Submitted".
**5.** Standard License Header: There is no standard license header for the license.
**6.** License Request Url: http://tools.spdx.org/app/license_requests/106
**7.** URL(s): https://creativecommons.org/licenses/by-nc-sa/3.0/igo/legalcode
**8.** OSI Status: Not Submitted
**9.** Example Projects: https://downloadapi.paperflite.com/api/2.0/shared_url/5fb7d811f52491706d1cdab4/asset/5fb7d811f52491706d1cdab3/download

### PR DESCRIPTION
**Pull request by tigerswell**
Closes #1210.

### CODE REVIEW

**Comment by johnmhoran** [comment]
Could the failure be related to something as mundane as the different indentations for the `item` tags from line 54 to line 55?

**Comment by goneall** [comment]
The issue is with section 1.g.   In the XML, the text is:

```
<bullet>g.</bullet> "Distribute" means the activity of making publicly available the Work (or copies of the Work), as applicable, by sale, rental, public lending or any other known form of transfer of ownership or possession of the Work or copy of the Work.
```

The test file contains:
```
g. "Distribute" means the activity of making publicly available the Work or Adaptation (or copies of the Work or Adaptation), as applicable, by sale, rental, public lending or any other known form of transfer of ownership or possession of the Work or copy of the Work.
```

Notice that the test file has the additional text `or Adaptation` after `the Work`.

**Comment by swinslow** [comment]
Good eyes, thanks @goneall  :)

I see that the tests are failing still, I'm taking a closer look at it now.

**Comment by swinslow** [comment]
Looks like there were two minor issues for the latest commit:
* section 3.a -- in the test text (and the license itself) this subsection ends with `; and`, but in the XML it ended with a period
* notice at the bottom -- in the XML it correctly included the header `Creative Commons Notice`, but in the test text that was missing

The tests appear to be passing now on my local machine. I'll push an update to this PR to make sure it works...

**Comment by swinslow** [comment]
Okay, now I'm at a loss. When I run the tests on my local machine, they are now passing as of commit 01fb42c. But here in the CI system, they appear to be failing. I've stared at the line that's being flagged and I really can't see a problem  :)

@goneall, I'd welcome your thoughts on this when you have a minute. I'm going to move this issue to 3.15 so definitely not a rush, but would be interested to know if you can see something I'm missing!

**Comment by swinslow** [comment]
OH, wait, I think maybe this is my fault. The one that's failing now isn't CC-BY-NC-SA-3.0-IGO, it's CC-BY-NC-ND-3.0-IGO. The IDs were very close and I typed the wrong one.

I think probably this is an incomplete merge of prior commits, from me not pulling everything into the branch. Let me give this another go...

**Comment by swinslow** [comment]
I think I'm finally seeing what's really happening now  :)

It looks like b95b4ef and c591e5c were accidentally made as updates to the -ND version of the license, rather than the -SA version. Because of that, the -SA flavor is now working but -ND is not.

To avoid further confusion, I am going to try creating a separate PR and pull in the edits from @tigerswell up to that point, rather than having the thread of changes and reversions to the -ND license in this branch. (Also because I realize that my own follow-up commit in this branch referred to the wrong license as well...)

**Comment by swinslow** [comment]
Okay -- the tests are passing in #1313. So I'm going to close this PR and merge that one instead.

@tigerswell thank you so much for preparing this! We're using all of the work you did and the commits will still be credited to you, they'll just be getting merged in #1313 instead of in this PR.

**Pull request closed without merging**
