### PR TITLE
Addresses issue #2431 (CC licenses issue)

### PR DESCRIPTION
**Pull request by pmonks**
Comments / suggestions / edits welcome.

I checked all CC-BY-*-3.0 licenses, and only modified those with text renditions published by Creative Commons (CC doesn't publish all of their license variations in plain text, sadly).

### CODE REVIEW

**Comment by xsuchy** [comment]
Tests are failing. Can you edit the tests in test/simpleTestForGenerator/ too?
I guess that the tests should match even the optional text.

**Comment by pmonks** [comment]
@xsuchy how do I run the tests locally, so I can confirm I've fixed them before updating the PR?

**Comment by xsuchy** [comment]
```
./test-one-license CC-BY-SA-3.0
```

**Comment by pmonks** [comment]
This is now fixed, however the `CC-BY-3.0` test is still failing due to an unrelated issue in that template.  I'll raise a separate issue for that.

**Comment by xsuchy** [comment]
Note that I am not a huge fan of rewriting something just because - i.e. you reformated all the tests, that makes the diff very ugly.
And you are mixing two issues together. Yes, the bullet e. is different in CC legal text  https://creativecommons.org/licenses/by/3.0/legalcode.txt compared to what we have in XML and test, but that is for different discussion. So in this PR we should stick just to adding the missing header. Nothing else.

**Comment by pmonks** [comment]
@xsuchy

> Note that I am not a huge fan of rewriting something just because - i.e. you reformated all the tests, that makes the diff very ugly.

I copied the license texts from the license author verbatim into the tests (for example [here's the official `CC-BY-3.0` license text](https://creativecommons.org/licenses/by/3.0/legalcode.txt) that I copied into the `CC-BY-3.0.txt` file in the tests in this PR).  I consider it **exceptionally** bad practice to edit those canonical texts *in any way*, but of course this PR is editable so you may do so if you prefer introducing inconsistencies in order to preserve diff aesthetics.

> And you are mixing two issues together. Yes, the bullet e. is different in CC legal text https://creativecommons.org/licenses/by/3.0/legalcode.txt compared to what we have in XML and test, but that is for different discussion. So in this PR we should stick just to adding the missing header. Nothing else.

I'm not mixing anything together.  As I [clearly wrote above](https://github.com/spdx/license-list-XML/pull/2441#issuecomment-2046064208), "I'll raise a separate issue for that."  That issue was indeed raised shortly after I wrote that, and can be [seen here](https://github.com/spdx/license-list-XML/issues/2445).

**Comment by jlovejoy** [comment]
hey @pmonks and @xsuchy - I'm a bit lost on the last few comments about re-writing tests?? Or maybe there is a typo somewhere and that was really about "texts"?

In any case, my understanding of the original issue #2431 was to add the missing title text, which @pmonks did in the xml files. But the text files also needed to be updated. In doing so, it looks like @pmonks cut and pasted the whole license from the CC text files which has line breaks where we didn't before (which makes the diff look messy, but it's really not a substantive change) - is that right?

Also just read the issue with CC-BY-3.0 - @pmonks - can you just delete the xml file for that license from this PR? We are going to need to update that otherwise and then this will pass tests.

**Comment by pmonks** [comment]
> In any case, my understanding of the original issue #2431 was to add the missing title text, which @pmonks did in the xml files. But the text files also needed to be updated. In doing so, it looks like @pmonks cut and pasted the whole license from the CC text files which has line breaks where we didn't before (which makes the diff look messy, but it's really not a substantive change) - is that right?

That's correct, yes. In doing so, I also just happened to discover issue #2445 (which is unrelated to this issue & PR, except by virtue of colliding via the updated `CC-BY-3.0` text file).

**Comment by jlovejoy** [comment]
ugh, I think I messed this up. I was trying to delete the CC-BY-3.0 file from this PR, but I think I just simply deleted it. Given the CC-CY-3.0 has other issues and there is now a PR to address that separately, we can not include those files here. Let me see how I can un-do or otherwise clean-up my mess...

**Comment by pmonks** [comment]
Or maybe just close this PR without merging it?  I _think_ (but am not 100% sure) that because I already merged it into PR #2445 the changes that are here will come through via that PR anyway.

**Comment by jlovejoy** [comment]
ah, thanks @pmonks - I will close this one then. Sorry for screwing it up and making more work

**Pull request closed without merging**
