### PR TITLE
XPP: add markup for spelling error

### PR DESCRIPTION
**Pull request by jlovejoy**
markup for University or Univeristy, plus and/or

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Review by swinslow — CHANGES_REQUESTED** [review]
I'm not certain why this is failing. I suspect it _might_ have something to do with embedding the `<alt>` tags in the middle of a quoted string in the XML file.

If so, then this might be fixable by changing each `"` mark to `&quot;` in the relevant bits surrounding the "Indiana University" parts of the text.

**Comment by jlovejoy** [comment]
thanks @swinslow - trying that...

**Comment by swinslow** [comment]
Hmm... still appears to be failing. I think we're going to need more time to sort this out, so I'm moving it to 3.20.

**Comment by swinslow** [comment]
OK, so I think this one has been failing because of the same problem with the Validate schema tests that we fixed last week. I'll update this PR so we can re-run those updated tests...

**Review by swinslow — APPROVED** [review]

**Pull request merged**
