### PR TITLE
minor text updates

### PR DESCRIPTION
**Pull request by jlovejoy**
minor text updates to further align with https://spdx.org/spdx-license-list/request-new-license

### CODE REVIEW

**Comment by jlovejoy** [comment]
as per https://wiki.spdx.org/view/Legal_Team/Minutes/2018-07-12 discussion, we were going to update this file, and then add a link to CONTRIBUTING to webpage (https://spdx.org/spdx-license-list/request-new-license), update links elsewhere, so we can eventually get rid of webpage and just have one place for this info

Links to be update on following pages:

- [ ] https://spdx.org/spdx-license-list/license-list-overview

- [ ] https://spdx.org/licenses/ (in template)

- [ ] https://spdx.org/licenses/exceptions-index.html (in template)

anywhere else?

**Comment by jlovejoy** [comment]
@swinslow , @bradleeedmondson  - can you sanity check this, then I'll merge, and change the webpage to simply have a link to this page (confirm that was our plan)

**Comment by swinslow** [comment]
@jlovejoy Jilayne, this looks good to me, and agreed that this is what I understood we planned to do. 

I'll check elsewhere on the webpage to see if we need to update other links, but I think this can proceed in the meantime. Thanks!

**Comment by swinslow** [comment]
A couple more links on the website to be updated - I can point these to CONTRIBUTING.md after this PR is merged:

- [FAQ page](https://spdx.org/frequently-asked-questions-faq-0), next-to-last question (just above "Tools")
- [Appendix I of the spec](https://github.com/spdx/spdx-spec/blob/master/chapters/appendix-I-SPDX-license-list.md) also has the link, because the license list is currently embedded in the spec as an appendix.

**Pull request merged**
