### PR TITLE
Add EUPL-1.2

### PR DESCRIPTION
**Pull request by silverhook**
Fixes https://github.com/spdx/license-list-XML/issues/505

Caveat:

The following line does point to the right (although unexpected) URL where OSI lists the EUPL-1.2:
```xml
<crossRef>http://www.opensource.org/licenses/EUPL-1.1</crossRef>
```
But will probably have to be changed once the OSI fixes the URL.

### CODE REVIEW

**Comment by silverhook** [comment]
@zvr, I think it’s ready for your ~~butchering~~ review :sweat_smile:

**Comment by silverhook** [comment]
OSI confirmed that they are aware of the URL issue mentioned above and are going to fix it.

**Comment by zvr** [comment]
Only comments here, I'm not changing any of the text myself :-)

* line 9, you can delete the "&qid=..." part of the URL to have it smaller (and the '&' character might be not ok
* lines 17-19, this is the copyright of the license, so it shouldn't be replaceable by the copyright of the content under the license. Yes, I realize that the other versions of EUPL also suffer from the same bug, I'll open an issue
* I would personally replace dashes and smart quotes with their ASCII equivalent, but I don't know whether we always do it. Maybe @goneall or @wking can advise...

Everything else, structure-wise and content-wise looks fine -- although I didn't check the original text word by word.

**Comment by zvr** [comment]
I've opened #523 for the copyrightText bug

**Comment by silverhook** [comment]
I think this addresses your (first two) comments.

Regarding smart quotes and dashes, I found them in other licenses in the repo as well, so I left them in order to be as close to the original as possible.

Is there any convention on line length? I went with one line per `<p>`, but as this is XML, blank space is blank space, so I’m happy to shorten them up to be coherent with others.

Thank you for reviewing 😸

**Comment by zvr** [comment]
@silverhook  can you add me to your eupl-1.2 branch, so I can push a change?

**Comment by zvr** [comment]
Sorry, I brought the rest of the files up-to-date, because I had merged it already.

**Comment by zvr** [comment]
So, on your EUPL-1.2, do you need the `<p>` in the first `<item>`s ?
In lines 38 and 43 of the pretty-printed version...

**Comment by silverhook** [comment]
> So, on your EUPL-1.2, do you need the `<p>` in the first `<item>`s ?
In lines 38 and 43 of the pretty-printed version...

TBH, I simply followed the way it’s done in `EUPL-1.1.xml`, which also states:

``` xml
<list>
    <item>
        <p>Licensed under the EUPL V.1.1</p>
     </item>
     <item>
         <p>or has expressed by any other mean his willingness to license under the EUPL.</p>
     </item>
</list>
```

As for the license text. I did make sure to copy it word-to-word from the official text.

Just for doing better next time …is there any specific style or even tool that we should use for pretty printing in SPDX’s license XML?

**Comment by goneall** [comment]
> I would personally replace dashes and smart quotes with their ASCII equivalent, but I don't know whether we always do it.

No opinion on the dashes.

For the smart quotes, I would leave it as originally found just to preserve the original text.

The license matching algorithm in the SPDX tools normalizes all of the different quotes per the license matching guidelines.

**Comment by wking** [comment]
On Mon, Dec 18, 2017 at 08:39:30PM +0000, Matija Šuklje wrote:
> …is there any specific style or even tool that we should use for
> pretty printing in SPDX’s license XML?

More on this in #432.

**Comment by jlovejoy** [comment]
@silverhook @zvr - I'm confused! this issue is titled for adding EUPL-1.2, but there are 9 files changed... help

**Comment by wking** [comment]
> this issue is titled for adding EUPL-1.2, but there are 9 files changed…

In c12c2e2, @zvr [merged a more recent master commit into this feature branch][1].  Reverse merges like that can confuse GitHub, but this PR is only adding `EUPL-1.2` (despite GitHub's diff display):

```console
$ git diff --stat=40 c12c2e2^..origin/pr/511
 src/EUPL-1.2.xml | 499 +++++++++++++++
 1 file changed, 499 insertions(+)
```

[1]: https://github.com/spdx/license-list-XML/pull/511#issuecomment-352380611

**Pull request merged**
