### PR TITLE
GPL-2.0*: Remove erroneous whitespace from around <optional>

### PR DESCRIPTION
**Pull request by wking**
Recover from some whitespace which was accidentally introduced by a0879e6e (#553).

This PR is similar to #565, which is restoring whitespace which was accidentally removed by a0879e6e.

### CODE REVIEW

**Comment by wking** [comment]
Does milestoning this 3.1 mean that I should switch to `<alt>` to match folks who decide to use `02110-1301 ,` (with the space that I'm trying to use in this commit)?  That would now technically match our template and *recommended* text, while `02110-1301,` would not match our template.

**Comment by goneall** [comment]
> Does milestoning this 3.1 mean that I should switch to <alt> to match folks who decide to use 02110-1301 , (with the space that I'm trying to use in this commit)? 

What space is ignored when matching, so no need to introduce an `<alt...` tag

**Comment by wking** [comment]
> [White] space is ignored when matching...

I agree that a single space, multiple spaces, tabs and spaces, etc. are equivalent.  I'm less clear on adding whitespace where there was none, or removing whitespace where the was some.  Do we really want to ignore those too?

**Comment by jlovejoy** [comment]
@goneall is the one to give the definitive answer here, as it depends on how tools deal with the given white space scenario.

**Comment by goneall** [comment]
Finally getting back to this.  

This is a bit of a grey area for the tooling.  The matching guidelines state that whitespace can be ignored.   Most tool implementations tokenize based on the punctuation characters in addition to the white space, however this isn't specified in the matching guidelines.  The SPDX tools will handle this fine.  There is a small probability that other tools using the matching guidelines will not be able to match.

Since there is also a cosmetic improvement removing extra spaces, I would suggest merging this PR.

@wking If you wouldn't mind rebasing, I'll merge.

**Comment by wking** [comment]
Rebased with e407fc6 → 744e9ee.

**Pull request merged**
