### PR TITLE
MIT: add markup for disclaimer

### PR DESCRIPTION
**Pull request by jlovejoy**
add markup for disclaimer for copyright/author name

### CODE REVIEW

**Comment by jlovejoy** [comment]
as per #866 - also want to add markup to MIT license to accommodate differences in how "the 'Software'" is defined:

original says: "to any person obtaining a copy of this software and associated documentation files (the "Software")"

variation: "to any person obtaining a copy of this source file (the "Software")"

This variant of MIT is used in the Linux kernel
see: https://github.com/torvalds/linux/blob/master/drivers/block/xen-blkfront.c

can someone with better schema/markup skills help with this part? I'm not sure how to indicate one option or another (versus simply replaceable) - @zvr ??

**Comment by silverhook** [comment]
I would say the `<alt match=".+" name="copyright">` should stretch also over line 12, to include the first line of the copyright statement. Unless I’m 

My RegExp game is pretty weak, but if unless I’m mistaken, just matching the two options you list could be done with simply:

```regexp
this software and associated documentation files \(the "Software"\)|this source file \(the "Software"\)
```

Another approach would be perhaps:

```rexexp
copy of .*? (\(the "Software"\)){1}
```

**Comment by jlovejoy** [comment]
discussed this on 6/27 call - will merge for markup for disclaimer. But difference in definition of "the Software" could be legally different, so holding on that (currently only found in one kernel file)

**Comment by swinslow** [comment]
I agree with merging this for the disclaimer markup change.

**Comment by jlovejoy** [comment]
@swinslow - can you merge as per our - someone-different-merges policy?  :)

**Comment by swinslow** [comment]
done  =)

**Pull request merged**
