### PR TITLE
Revise FSFUL.xml to accommodate config.status variant

### LINKED ISSUE #2219: Revise FSFUL.xml to accommodate "config.status script" variant
There are what I believe are generated Automake files that insert a license that is mostly identical to `FSFUL` except the name of the referenced file is different. In the example I am currently looking at, it's

```
Copyright (C) 2021 Free Software Foundation, Inc.
This config.status script is free software; the Free Software Foundation
gives unlimited permission to copy, distribute and modify it.
```

although I think there may be other examples using other file names. 

You can verify this by doing a search for "This config.status script is free software".

### PR DESCRIPTION
**Pull request by richardfontana**
Fixes #2219

### CODE REVIEW

**Comment by richardfontana** [comment]
Not sure if I did this right. :)

**Comment by jlovejoy** [comment]
This markup means it can only be "config.status" or "configure" - we could also denote this by replaceable text without the specific options.  But I think this is fine as it's the only two variations we've come across and if we came across another, then we can determine how to adjust at that time

**Comment by jlovejoy** [comment]
FYI @swinslow  for awareness

**Comment by richardfontana** [comment]
I think it should be replaceable text - I just found another variant, using the file name `config.lt`.

**Comment by jlovejoy** [comment]
@richardfontana - can you change this to add the other variant you found or just change it to `<alt match=".+"`

**Pull request merged**
