### PR TITLE
Correcting some items' order in SugarCRM-1.1.3.xml

### PR DESCRIPTION
**Pull request by camillem**
Hi, 
Order of 1.9-A and 1.9-B had been reversed. 2.2-a was also at the wrong end of the list.

### CODE REVIEW

**Comment by jlovejoy** [comment]
this needs a closer look, including as to why it's failing on the build

**Comment by goneall** [comment]
Here's the error from the validation:

```
Test for license SugarCRM-1.1.3 failed: Test for license ID SugarCRM-1.1.3 failed due to difference found Normal text of license does not match starting at line #31 column #40 "any" when comparing to template text " Any addition to or deletion from the contents of a file containing Original Code or previous Modifi..."
```

From looking at the changes, it looks like the license XML was changed but there were no matching changes to the test file https://github.com/spdx/license-list-XML/blob/master/test/simpleTestForGenerator/SugarCRM-1.1.3.txt

**Comment by goneall** [comment]
Just another note - if there are license texts similar to those in the current test file, we'll need to add variable text markers to allow both versions to match.

**Comment by camillem** [comment]
Sorry, I was not aware of the tests. Depending on what's more convenient for you, I can create a new clean PR with the tests also corrected or add commits to this one. 
And actually, it seems that section 1.0.1 is also missing in current SDPX version as compared to https://web.archive.org/web/20110722045536/http://www.sugarcrm.com/crm/SPL

**Comment by goneall** [comment]
> Depending on what's more convenient for you, I can create a new clean PR with the tests also corrected or add commits to this one.

Either approach is fine

**Comment by jlovejoy** [comment]
oddly, this is how it appears in the standard text: https://www.sugarcrm.com/legal/sugarcrm-public-license/

(although we do need to update the URL.

Given that is how it appears in the wild, I think we should just leave it.  Sorry this took so long... !!!

**Pull request closed without merging**
