### PR TITLE
Create license-match.md

### PR DESCRIPTION
**Pull request by jlovejoy**
first commit to add guidance on determining match or not

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by swinslow** [comment]
Probably worth discussing further, but here are a few initial thoughts:
* I'd suggest we include links to any tools that we're recommending people to use as well as the matching guidelines themselves
* Is it worth also suggesting that people run a direct comparison themselves for greater certainty, using something like LibreOffice / Word?
* Similarly, might suggest using web searches for `"text to match" site:spdx.org` or something similar

**Comment by jlovejoy** [comment]
@swinslow - yup, I need to add stuff. I took some notes in a Google doc while I was reviewing the various HPND variants, etc. Need to go back and add generalized stuff from that here. Will tag you when I do for review!

**Comment by swinslow** [comment]
Thanks @jlovejoy! To avoid merging accidentally I switched this to "draft," we can change it back to a regular PR once it's ready for review.

**Comment by jlovejoy** [comment]
yup, sounds good. I want to add to this while it's fresh in my mind, but not critical for the next couple days!

**Pull request merged**
