### PR TITLE
Update Linux-man-pages-1-para.xml

### LINKED ISSUE #1955: New license request: Linux-man-pages-1-para [SPDX-Online-Tools]
**1.** License Name: Linux man-pages One Paragraph
**2.** Short identifier: Linux-man-pages-one-para
**3.** License Author or steward: Unknown
**4.** Comments: This license appears in several Linux man-pages under the name of VERBATIM_ONE_PARA
**5.** License Request Url: http://tools.spdx.org/app/license_requests/231
**6.** URL(s): https://github.com/mkerrisk/man-pages/blob/master/man2/getcpu.2#L4-L7
**7.** OSI Status: Unknown
**8.** Example Projects: https://github.com/mkerrisk/man-pages

### PR DESCRIPTION
**Pull request by jlovejoy**
fixes #1955 

updates to name and id as per request by maintainer of man-pages, @alejandro-colomar 

note @adobes1

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
I change my original suggestion, and now suggest `Linux-man-pages-copyleft-1-para` (with a full name of: `Linux man-pages Copyleft (1-paragraph variation)`), for consistency with <https://github.com/spdx/license-list-XML/issues/1947>.  Sorry for the inconvenience :)

**Comment by alejandro-colomar** [comment]
BTW, you'll also need to `mv src/Linux-man-pages-one-para.xml src/Linux-man-pages-copyleft-1-para.xml`.

**Comment by jlovejoy** [comment]
ok @alejandro-colomar - last change of mind, please!

I did leave off "variation" in the full name as I don't think that's necessary

Please give a thumbs up and then we'll merge this (again) :)

**Comment by alejandro-colomar** [comment]
Actually, as @g-branden-robinson suggested in the other thread, maybe it's better to be specific as to how does it differ from Linux-man-pages-copyleft, instead of how many paragraphs it has, as some future license may pick a different single paragraph from it.

How about this? `Linux-man-pages-copyleft-no-mod` - `Linux man-pages Copyleft (no modifications)`  The reason is that this variant only allows verbatim copies, while the longer variants allow modifications under the same license.

**Comment by jlovejoy** [comment]
@alejandro-colomar - "no modifications" sounds like modifications are not allowed, which is not the case so I think that could be misleading

**Comment by jlovejoy** [comment]
I think either `Linux-man-pages-one-para` or `Linux-man-pages-1-para` is the way to go. I don't see how "copyleft" really fits here as this license is much less specific to that end than https://spdx.org/licenses/Linux-man-pages-copyleft.html

Can we please decide on one of those and get this closed?  :)

**Comment by g-branden-robinson** [comment]
My name was spoken, thus I am summoned in a puff of brimstone.  I agree with @jlovejoy that "no-mod" and "no modifications" are misleading (show-stopperingly so in my opinion, but SPDX hasn't been my show for years).

However I disagree that the fact of copyleft is not material here.  Reviewing the text:

`Permission is granted to distribute possibly modified copies of this page provided the header is included verbatim, and in case of nontrivial modification author and date of the modification is added to the header.`

If the license terms are part of the "header", as they do appear to be, then this is in fact a copyleft.  "Permission is granted" to all who read the terms (implicitly: as long as they uphold said terms).  No intermediate licensee B between licensees A and C can delete any granted permission, and that is the essence of copyleft  (IANAL; TINLA).

As with issue #1947 I think it is a bad idea to put the length of the license text in paragraphs into the license description, short or long.  What happens when some clever person re-uses some license text with a paragraph break deleted?

It is becoming clear to me that the "Linux man-pages copyleft" is not one license but several.  There appears to be a problem of proliferation.  Because @alejandro-colomar is an energetic person, I propose suspending the addition of further Linux man-pages copyleft licenses to SPDX until he has had a chance to attack this problem.  I think it would be a better world for everyone if all the man pages that project distributes were under terms already in the SPDX license list.  As a sometime contributor to that project's mailing list, I can perhaps be of some assistance.

**Comment by alejandro-colomar** [comment]
> @alejandro-colomar - "no modifications" sounds like modifications are not allowed, which is not the case so I think that could be misleading

Sorry, I misread.  I thought I had read the first paragraph of Linux-man-pages-copyleft, which is different.

**Comment by alejandro-colomar** [comment]
> My name was spoken, thus I am summoned in a puff of brimstone. I agree with @jlovejoy that "no-mod" and "no modifications" are misleading (show-stopperingly so in my opinion, but I haven't been an SPDX cast or crew member for years).
> 
> However I disagree that the fact of copyleft is not material here. Reviewing the text:
> 
> `Permission is granted to distribute possibly modified copies of this page provided the header is included verbatim, and in case of nontrivial modification author and date of the modification is added to the header.`
> 
> If the license terms are part of the "header", as they do appear to be, then this is in fact a copyleft. "Permission is granted" to all who read the terms (implicitly: as long as they uphold said terms). No intermediate licensee B between licensees A and C can delete any granted permission, and that is the essence of copyleft (IANAL; TINLA).
> 
> As with issue #1947 I think it is a bad idea to put the length of the license text in paragraphs into the license description, short or long. What happens when some clever person re-uses some license text with a paragraph break deleted, or modifies this one to turn it into two paragraphs, perhaps at "verbatim. ¶In case of nontrivial"?
> 
> It is becoming clear to me that the "Linux man-pages copyleft" is not one license but several. There appears to be a problem of proliferation. Because @alejandro-colomar is an energetic person, I propose suspending the addition of further Linux man-pages copyleft licenses to SPDX until he has had a chance to attack this problem. I think it would be a better world for everyone if all the man pages that project distributes were under terms already in the SPDX license list. As a sometime contributor to that project's mailing list, I can perhaps be of some assistance.

@g-branden-robinson Do you propose that we start a mission in linux-man@ of asking Copyleft holders to relicense into the "standard" version of the license?

**Comment by g-branden-robinson** [comment]
> Do you propose that we start a mission in linux-man@ of asking Copyleft holders to relicense into the "standard" version of the license?

@alejandro-colomar, pretty much, and I see you already have this underway.  :)

**Comment by jlovejoy** [comment]
see #1955 for final discussion/rationale on name :)

**Review by swinslow — APPROVED** [review]
It was a long journey but looks like we're good here  :)

**Pull request merged**
