### PR TITLE
Add CERN-OHL-{P,S,W}-2.0

### PR DESCRIPTION
**Pull request by kemitchell**
For @andrewjskatz.

These are very arguably the most important open licenses for COVID-19 relief work. I strongly support their immediate inclusion.

### CODE REVIEW

**Comment by kemitchell** [comment]
Official Texts: https://www.ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2

Issues: #1009, #1010, #1011

**Comment by kemitchell** [comment]
Tests passed. Good to go.

**Comment by swinslow** [comment]
@kemitchell Many thanks for preparing this so quickly. I'm about to leave a comment in the issue thread noting that I'm in favor of adding them for 3.9 (and encouraging input from others so that there's enough consensus to move forward).

For this PR, I reviewed briefly -- my only comment is about the version numbers. The license text itself uses "2"; the wiki page and @andrewjskatz's issue requests use "2.0"; but the PR uses "2.0.0". I defer to @andrewjskatz but I'd be inclined to use either "2" or "2.0" rather than "2.0.0" if that's the preferred usage by the license stewards.

**Comment by kemitchell** [comment]
Renamed to `*-2.0`s. And I believe @andrewjskatz has more thoughts on IDs that we should air before merging.

**Comment by kemitchell** [comment]
Ah, so I see I totally missed @andrewjskatz's on identifiers. He submitted for `CERN-OHL-2.0-S`, `CERN-OHL-2.0-S`, and `CERN-OHL-2.0-P`, which show up in the issues. But I used identifiers with the version numbers at the end.

I'm agnostic.@andrewjskatz should weigh in.

**Comment by andrewjskatz** [comment]
I’m heading to bed now, so I’ll get onto this tomorrow. Thanks Kyle. 

- Andrew

Andrew Katz
+44 7970 835001
I'm emailing from my smartphone, so please excuse terseness!

**Comment by Juul** [comment]
I'd really appreciate if this was merged. I'm part of a team working on a reverse-engineered interface to allow old qPCR machines to be re-used with modern computers in order to rapidly scale COVID-19 testing and a CERN OHL 2.0 license is the obvious choice for our work.

**Comment by j-sp** [comment]
There are many groups out there doing COVID-19 relief work under these licenses. Two examples:
https://ohwr.org/openbreath/lungventilator/wikis/home
https://ohwr.org/project/ventilatorpal/wikis/home

**Comment by penyuan** [comment]
This is not only a great, but also *crucial*, addition to the SPDX identifiers. Hope it will be merged soon!

**Comment by garcialasheras** [comment]
I would love to see this PR merged!

The CERN OHL license has been around for several years now and, AFAIK, the 2.0 version includes several improvements based upon the feedback of actual users.

It's worth to highlight that not only some of the most advanced instrumentation hardware for Big Science experiments is licensed under CERN OHL, but this is steadily becoming a "de-facto" standard in the Open Source Hardware community.

**Comment by rwb27** [comment]
We used the CERN OHL for all our hardware projects, and would love to see it merged :)

**Comment by jtc42** [comment]
> We used the CERN OHL for all our hardware projects, and would love to see it merged :)

Second this. Would be great to see.

**Comment by julianstirling** [comment]
We are using the CERN OHL many projects. We would love for this to be merged.

**Comment by swinslow** [comment]
@andrewjskatz Did you have other input on the identifiers for this? This PR would use:

* CERN-OHL-P-2.0
* CERN-OHL-S-2.0
* CERN-OHL-W-2.0

which I think is in line with what you were looking for, but as license author/steward wanted to get your confirmation given the earlier comments above.

Separately, I've asked others who participate in the SPDX legal team to weigh in at #1011 on adding the licenses (so that it's more than just me giving the go-ahead). Once we get other OKs and assuming no objections, we should be in a position to proceed if you're good with the PR and identifiers here.

**Comment by mwweinberg** [comment]
I also want to support adding these new CERN licenses.  These are the most mature OSHW licenses and the Open Source Hardware Association is in the process of adding them to the open source hardware certification program.  We would love to be able to take the opportunity to list the SPDX identifiers when we do so.

**Comment by kenhara** [comment]
In our research, @OSHdata has concluded that increased awareness of Open Source Hardware-specific license options is crucial to facilitating adoption of those licenses. Greater awareness of mature licenses like from CERN will make the Open Hardware community stronger. GitHub making this change will be a big help. Thank you!!

**Comment by janluctavares** [comment]
In the development of Open Hardware Projects at [CTA](http://cta.if.ufrgs.br/capa/), in Brazil, we adopted the CERN OHL in some of them and we see this license as very important to open hardware projects. We would love to see it included in the SPDX.

**Comment by andrewjskatz** [comment]
Ok, so I just spoke with Javier Serrano. @swinslow, we're happy with the license identifiers  in this PR:

CERN-OHL-P-2.0
CERN-OHL-S-2.0
CERN-OHL-W-2.0

Could we also have clarification that we don't need to do anything for people to be able use:

CERN-OHL-P-2.0+
CERN-OHL-S-2.0+
CERN-OHL-W-2.0+

For the "or later" option. This seems to follow from https://spdx.org/ids-how, but Javier has asked me to confirm.

Many thanks!

**Comment by zvr** [comment]
Yes, nothing needed for the "+" to be used to mean "or later version".

... which raises a question: if there is a use (past or future) of `CERN-OHL-1.2+` or `CERN-OHL-1.1+`, to which of the 2.0 licenses does it translate?

**Comment by j-sp** [comment]
From https://ohwr.org/cern_ohl_s_v2.txt:
> If no variant is specified, the Covered Source shall be treated as being released under CERN-OHL-S.

**Comment by swinslow** [comment]
Discussed on 2020-05-07 SPDX legal team call, agreed to add these. Thank you @andrewjskatz! (and to all others who commented on this thread)

I see the PR is already passing so I'll go ahead and merge it (thank you @kemitchell!)

**Pull request merged**
