### PR TITLE
Add BSD-3-Clause-Sun license

### PR DESCRIPTION
**Pull request by mkoncek**
Related: #2081
Notes:
* **TODO** at `crossRefs`, I didn't know what to fill in
* `copyrightText / list / item number 3`, I am unsure if it qualifies as an item with an empty bullet or if the text belongs to the following `<p>`
* I used name **BSD 3-Clause Sun Microsystems** instead of **BSD 3-Clause Sun** because I think the word Sun itself is too vague.

### CODE REVIEW

**Comment by jlovejoy** [comment]
thanks @mkoncek !

For crossref - use https://github.com/xmlark/msv/blob/b9316e2f2270bc1606952ea4939ec87fbba157f3/xsdlib/src/main/java/com/sun/msv/datatype/regexp/InternalImpl.java

As for the third clause, I'd just end the <list> after the second clause, since that will reflect how it is in the file above

name update for full name sounds good

**Comment by mkoncek** [comment]
> As for the third clause, I'd just end the after the second clause, since that will reflect how it is in the file above

Well, in that case, isn't it actually a 2-Clause BSD-style license?
I mean is the 2- vs. 3-Clause name related to how many clauses the license text has or how similar the license is to the pure 2- and 3-Clause licenses?
The license has 2 clauses but the text is more similar to the 3-Clause version.

**Comment by mkoncek** [comment]
Rebased:
* set `isOsiApproved="false"`
* added `crossRef`
* moved the 3rd list item into a separate paragraph

**Comment by jlovejoy** [comment]
> > As for the third clause, I'd just end the after the second clause, since that will reflect how it is in the file above
> 
> Well, in that case, isn't it actually a 2-Clause BSD-style license? I mean is the 2- vs. 3-Clause name related to how many clauses the license text has or how similar the license is to the pure 2- and 3-Clause licenses? The license has 2 clauses but the text is more similar to the 3-Clause version.

well, it's not really just formatting that determines number of clauses. :)

**Pull request merged**
