### PR TITLE
AGPL-1.0.xml: fix license name

### PR DESCRIPTION
**Pull request by vargenau**
Change license name from "Affero General Public License v1.0" to "Affero General Public License v1.0 only". Then we have the same license name for AGPL-1.0.xml and AGPL-1.0-only.xml (as it is already the case for the GPL licenses).

Signed-off-by: Marc-Etienne Vargenau <marc-etienne.vargenau@nokia.com>

### CODE REVIEW

**Review by swinslow — APPROVED** [review]

**Review by swinslow — COMMENTED** [review]
Actually, although I approved this a moment ago, in retrospect I'm not certain about this one.

Part of the reason that `GPL-1.0`, `GPL-2.0`, etc. had `only` in their name is because originally there were separate `GPL-1.0+`, `GPL-2.0+`, etc. identifiers actually on the license list. I don't know the history but I assume those predated `+` being an operator in the license expression syntax.

Put another way, the deprecated "AGPL-1.0" identifier could have correctly had `+` appended to the end of it, so I'm not sure whether the intent was for `AGPL-1.0` to have "only" appended to the end of its name.

@jlovejoy Do you have any thoughts here? Personally I don't see a particular problem with adding "only" now, but didn't want to do something that might have already been considered in the past.

**Comment by jlovejoy** [comment]
ok, so the GFDL licenses that @vargenau has updated here were deprecated as of 3.0
but you can see the family of LGPL and GPL licenses have been deprecated (and updated) at two points in the past: 2.0rc2 and 3.0
this is b/c prior to 2.0rc2 - we didn't have operators, so we had GPL-2.0 and GPL-2.0+ on the list. With the addition of operators (e..g, the + operator), GPL-2.0+ (and the like) were deprecated, but GPL-2.0 remained with the same meaning (only).

In the meantime, the GFDL didn't have this same evolution. I'd have to dig back in the archives, but I don't believe we ever had GFDL-x.y+ on the list. But as of 3.0, we updated ALL the GNU Licenses and added the "invariants" options for GFDLs as well.

In any case, while I appreciated @vargenau diligence here, I don't think we should update deprecated licenses. It's sort of irrelevant now, and in this case, it was all a bit unclear previously, so it would feel a bit like re-writing history.

**Comment by swinslow** [comment]
Thanks all -- closing as described at https://github.com/spdx/license-list-XML/issues/1676#issuecomment-1364537861.

**Comment by vargenau** [comment]
I agree with the reasoning.

Best wishing to all for 2023.

**Pull request closed without merging**
