### PR TITLE
Add Sendmail-8.23 and test

### LINKED ISSUE #678: New License: Sendmail v8.23
FYI, the SPDX version of the Sendmail Liense is 8.16.  The current version is 8.23 which contains additional language.  I have attached both (see email)

Here is the original URL for the Sendmail License 8.23 text that Tom Incorvia provided: 

https://www.proofpoint.com/sites/default/files/sendmail-license.pdf

### PR DESCRIPTION
**Pull request by swinslow**
Fixes #678 

Signed-off-by: Steve Winslow <swinslow@gmail.com>

### CODE REVIEW

**Comment by swinslow** [comment]
The CI build failed, but it looks like the license XML file + test file were fine. 
Looks like the failure was due to something with the deployment code: see https://travis-ci.org/spdx/license-list-XML/jobs/437154527

@goneall Do you have any thoughts what's going on here?

**Comment by jlovejoy** [comment]
@wking can you have a look at why this is failing?

**Comment by swinslow** [comment]
@wking FYI, I am getting the same Error 64 when I run `make validate-canonical-match` on the mainline master branch.

**Comment by goneall** [comment]
I found the issue - some of the warnings were not being ignored.  We need to add more ignored warnings to the list of ignored warning files.  I'll do a pull request later today which should address this.

**Comment by goneall** [comment]
Should be good to merge - build failures are fixed in the master branch.

**Comment by swinslow** [comment]
Hi Gary, do you know if there's a way for me to re-trigger the build check? It's still showing as failed here.

**Comment by goneall** [comment]
@swinslow It will still fail since this branch does not have the updated expected-warnings from the fix.  I would suggest going ahead and merging this with master.  The merge will trigger a new build which should work.

**Pull request merged**
