### PR TITLE
Automated PR for CECILL-2.0

### PR DESCRIPTION
**Pull request by myndzi**

### CODE REVIEW

**Comment by zvr** [comment]
Ehmmmm... since the author of the license has published an English version on http://www.cecill.info/licences/Licence_CeCILL_V2-en.html, with a specific mention "_The Agreement is drafted in both French and English and both versions are deemed authentic_", why do we include (only) the French one in our list?

**Comment by bradleeedmondson** [comment]
> why do we include (only) the French one in our list?

Good point -- unsure.

@jlovejoy Did we come to an official decision on multi-language licenses, or did we postpone that till after the next release?

**Comment by zvr** [comment]
English version available in #437

**Comment by goneall** [comment]
Closing PR - English version #437 supersedes.  See issue #438 which tracks language translations

**Pull request closed without merging**
