### PR TITLE
New License: Xdebug

### LINKED ISSUE #1718: New License: xdebug
https://github.com/xdebug/xdebug/blob/master/LICENSE is a match to https://spdx.org/licenses/PHP-3.01.html but for the names

I think we can add some markup and accommodate. 

Also wondering if the last 3 lines with the contact info are really part of the licenses or should simply be optional?

(relates to https://gitlab.com/fedora/legal/fedora-license-data/-/issues/95 )

### PR DESCRIPTION
**Pull request by jlovejoy**
fixes #1718

Signed-off-by: Jilayne Lovejoy

### CODE REVIEW

**Comment by jlovejoy** [comment]
@swinslow  @goneall - not sure if we decided on how to deal with  ------- scenarios and if I did this right (for now) by making optional, but in any case it's failing - sigh

**Comment by goneall** [comment]
> not sure if we decided on how to deal with ------- scenarios and if I did this right (for now) by making optional, but in any case it's failing - sigh

I added code to the license compare to ignore any 3 or more repeating characters `---`, `===`, `___` - so no need to make it optional to pass the CI (unless there's a bug in the matcher).

**Comment by jlovejoy** [comment]
@goneall - not sure why this is failing now...

**Comment by goneall** [comment]
@jlovejoy It looks like either a bug in the license list publisher or we don't have the latest version merged.

I'll take a look at it over the weekend.

**Comment by goneall** [comment]
@jlovejoy Indeed this is a recently introduced bug in the license list publisher.

I'll publish a new version soon that should fix this check.

**Comment by goneall** [comment]
@jlovejoy - The new license list publisher is merged into main.  If you can merge that into your local repo / branch, it should pass the test (at least it did on my local machine).

**Comment by jlovejoy** [comment]
@goneall - not sure what you mean above... but still can't sort this one out :(

**Comment by goneall** [comment]
> - not sure what you mean above... but still can't sort this one out :(

@jlovejoy on your local machine, checkout the branch [jlovejoy:xdebug](https://github.com/jlovejoy/license-list-XML/tree/xdebug)
Then do a `git rebase main` to bring in the new version of the tools
Then do a git push to update the xdebug branch.  It should pass after that.

**Comment by jlovejoy** [comment]
YEAH!!  now can @goneall  or @swinslow please merge this beast, please! :-p
phew!

**Pull request merged**
