### PR TITLE
Add C-UDA-1.0

### LINKED ISSUE #1133: New license request: C-UDA-1.0 [SPDX-Online-Tools]
**1.** License Name: Computational Use of Data Agreement v1.0
**2.** Short identifier: C-UDA-1.0
**3.** License Author or steward: Microsoft Open Data Campaign
**4.** Comments: The license was released by Microsoft's Open Data Campaign on 2019-11-07. I am not affiliated with them.

This license is becoming quite popular for academic datasets which are distributed alongside software. It allows researchers to use data for computational purposes (e.g. to train artificial intelligence / machine learning systems), and does not impose any restriction on the results. The data itself can be modified and redistributed under the same terms.

An example of why this license is so useful. For a research project I needed to use the text of several books. The publisher was willing to let me do that, but didn't want me releasing the data into the public as they were afraid a competitor might take the text and start printing their own editions of those books. By suggesting the use of this license, I was able to solve their concerns.

Examples of projects using this data:
* WLASL dataset, best paper honorable mention at WACV 2020: https://dxli94.github.io/WLASL/
* SLNSpeech dataset: http://cheertt.top/homepage/
* Microsoft American Sign Language Dataset: https://msropendata.com/datasets/edbe743b-2d96-4673-8f18-98c87bb26283
* Microsoft Speech Corpus for Indian Languages: https://msropendata.com/datasets/7230b4b1-912d-400e-be58-f84e0512985e
* Many other projects on the Microsoft Research Open Data repository: https://msropendata.com/datasets?sort=lastModified
**5.** Standard License Header: 
**6.** URL: https://github.com/microsoft/Computational-Use-of-Data-Agreement/blob/master/C-UDA-1.0.md
**7.** OSI Status: Not Submitted

### PR DESCRIPTION
**Pull request by swinslow**
Fixes #1133

Signed-off-by: Steve Winslow <steve@swinslow.net>

### CODE REVIEW

**Comment by swinslow** [comment]
Note that this should not be merged until #1133 is accepted.

**Comment by jlovejoy** [comment]
is #1133 resolved to add this license?

**Comment by jlovejoy** [comment]
accepted as per Feb 18th call - to be merged once CI is up and running

**Comment by swinslow** [comment]
replaced by #1213 to re-run CI; closing

**Pull request closed without merging**
