### PR TITLE
Add comment about broken link

### LINKED ISSUE #2291: Link in Fair.xml is obsolete
Fair.xml includes the <crossRef> link to: http://fairlicense.org
However, this redirects to another site which appears to have nothing to do with the Fair license and does not contain the text of the Fair license.

### PR DESCRIPTION
**Pull request by richardfontana**
This would fix #2291 (sort of).

### CODE REVIEW

**Review by goneall — APPROVED** [review]
Agree the comment is helpful.

**Comment by jlovejoy** [comment]
given that the link goes to a live link that is not related, let's just remove this one.

@richardfontana - do you want to just update this PR?

**Comment by richardfontana** [comment]
> given that the link goes to a live link that is not related, let's just remove this one.
> 
> @richardfontana - do you want to just update this PR?

Done (if I did this right)

**Comment by richardfontana** [comment]
Ugh forget it, I don't know how to fix this.

**Comment by jlovejoy** [comment]
yeah, I hear ya, I thought I could do it but not sure. Someone JUST put the instructions on how to do this in another PR... I should find that and copy it somewhere!

But yeah, for this change, probably faster to just make a new PR!

**Pull request closed without merging**
