### PR TITLE
Adding exception: Bison-exception-2.2

### PR DESCRIPTION
**Pull request by myndzi**

### CODE REVIEW

**Comment by jlovejoy** [comment]
@goneall we have a special tag for exceptions - I added it to Google doc, but noting here as an example. Also, can we have formatting in Notes tag/field?

**Comment by goneall** [comment]
@jlovejoy Thanks for pointing out the exception tag.  I missed that when we did the original XML tags and attributes list in google docs.  Would it be OK to change the name from "exception" to "licenseException" in the final version?  This would make it more consistent with the RDF class names.  We could continue using "exception" and convert it with the other terms that have changed.  BTW - I'm OK with "exception" if anyone feels strongly we should keep it shorter.

**Comment by goneall** [comment]
@jlovejoy Currently, the HTML generator for the spdx.org/licenses page treats notes as a plain text field and doesn't support formatting.

**Comment by bradleeedmondson** [comment]
I think it makes sense to merge all exceptions with "exception" now and convert to "licenseException" when we do the other tag conversions.

**Pull request merged**
