### PR TITLE
Add missing GPL-1.0+ deprecated license.  Resolve issue #544

### PR DESCRIPTION
**Pull request by goneall**
Signed-off-by: Gary O'Neall <gary@sourceauditor.com>

### CODE REVIEW

**Comment by zvr** [comment]
Now that we went back, should we replace
> <notes>DEPRECATED: Use License Expression Syntax to create equivalent license.</notes>

with:


> <notes>DEPRECATED: Use GPL-1.0-or-later </notes>

**Comment by wking** [comment]
> DEPRECATED: Use GPL-1.0-or-later

+1 to this in the short term, although I'm looking forward to structuring this with #392.

**Comment by goneall** [comment]
> DEPRECATED: Use GPL-1.0-or-later

Good catch.  Updated the PR with the corrected comment

**Comment by wking** [comment]
With this PR merged, can someone with write access delete branch `addgpl1p`?

**Pull request merged**
