### PR TITLE
Add license files for FreeBSD-DOC #1111

### PR DESCRIPTION
**Pull request by johnmhoran**
Signed-off-by: John M. Horan <johnmhoran@gmail.com>

### CODE REVIEW

**Comment by goneall** [comment]
The error doesn't make any sense to me either.  It seems like it is having a problem reading this [JSON Context](https://wking.github.io/fsf-api/schema/licenses.jsonld) file - which I'm able to access just fine.

I restarted the build to see if it may be a transient error.

**Comment by swinslow** [comment]
@goneall I wonder if for some reason Travis is now restricting doing remote pulls in some way, or from certain sites / using certain tools. Not sure that makes sense but just one thought.

I'm wondering if now is the right time for us to move to GitHub Actions (if there's any chance of getting time / assistance from @iamwillbar or others). Travis has continued to be problematic and they now have a header saying "Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com."

**Comment by swinslow** [comment]
@iamwillbar just to be clear, I know you are utterly swamped so I apologize for the request for even more of your time! And am extremely appreciative for anything you can do to help here.

**Comment by goneall** [comment]
I added issue #1176 to track the CI failures - please add any related findings, comments, suggestions to that issue.

**Comment by goneall** [comment]
@johnmhoran The build issue has been resolved in the master branch.  If you could merge the changes from master into this PR, it should resolve the issue.  Note that the builds have been migrated from travis-ci.org to travis-ci.com.

**Comment by johnmhoran** [comment]
Thanks @goneall , I'll give it a try.

**Comment by johnmhoran** [comment]
Hmmm.  I don't understand -- line 235 of the [failed build's output](https://travis-ci.com/github/spdx/license-list-XML/jobs/480230550) says

```
Test for license FreeBSD-DOC failed: Test for license ID FreeBSD-DOC failed due to difference found Normal text of license does not match starting at line #15 column #126 "operating" when comparing to template text " Redistributions in compiled form (transformed to other DTDs, converted to PDF, PostScript, RTF and ..."
```

This appears to be comparing different portions of the .xml and .txt?  I don't see any problems in the two files, but it's late and perhaps I'm just reading over it.  

@goneall  @swinslow Can you see what the problem is?

**Comment by swinslow** [comment]
Hi @johnmhoran, thanks -- let's look at this during the call later today, if you're available to join.

**Comment by goneall** [comment]
> This appears to be comparing different portions of the .xml and .txt?

The verification "compiles" the XML into a template which is used to compare the .txt file to the license template.  The error indicates the comparison failed.

In looking at the 2 files, I don't see the issue either.  It is possible this is a bug in the comparison algorithm.  The only thing unusual is the registration symbol after Posix.  I'll do a bit more digging later today.

**Comment by johnmhoran** [comment]
Thanks @goneall and @swinslow .

**Comment by goneall** [comment]
This issue is with `Technology — Portable` the long dash is interpreted differently in XML than in the text version.  This may be an encoding issue.  In the short term, we could change the long dash to a short dash.  I'll look into changing the matching tool to normalize all long dashes to short dashes.

**Comment by goneall** [comment]
I just added https://github.com/spdx/Spdx-Java-Library/issues/37 to track updating the tools to handle this case.

**Comment by johnmhoran** [comment]
Thanks @goneall .  I'll replace the long dash in the `.xml` and `.txt` files with a keyboard hyphen and give it a go.

**Comment by johnmhoran** [comment]
@goneall  Bummer.  The error message in the [latest failed build's output](https://travis-ci.com/github/spdx/license-list-XML/jobs/480388783) looks identical to the previous error message.  Line 235:

```
Test for license FreeBSD-DOC failed: Test for license ID FreeBSD-DOC failed due to difference found Normal text of license does not match starting at line #15 column #126 "operating" when comparing to template text " Redistributions in compiled form (transformed to other DTDs, converted to PDF, PostScript, RTF and ..."
```

**Comment by goneall** [comment]
@johnmhoran On closer inspection, it turned out not be the dash, but [thin space Unicode characters](https://www.compart.com/en/unicode/U+2009) on either side of the dash.

The XML side translates this into regular spaces and the test text file is left as is causing it not to match.

If you replace the thin space with a regular space in the test text file, it should work.

Attached is a text file with the thin spaces replaced which worked on my local system.
[FreeBSD-DOC.txt](https://github.com/spdx/license-list-XML/files/5928042/FreeBSD-DOC.txt)

**Comment by goneall** [comment]
BTW - You don't need to change the XML file.

Also, BTW, I updated the issue in the verification tools to translate thin spaces to regular spaces when matching.  It turns out the matching tool already handled the long dashes.

**Comment by johnmhoran** [comment]
@goneall Two comments: Thank you, and yikes!  I've not encountered a Unicode thin space before.  I'm guessing that's not an issue that's easy to identify -- would those thin spaces have been removed if I'd copied the original license text, pasted it into, say, notepad++, and copied it from there into my VSCode?

I've deleted the spaces on either side of the hyphen and hit the space bar instead -- hopefully that generated non-"thin" spaces.  We'll see -- pushing shortly.

**Comment by goneall** [comment]
> I've not encountered a Unicode thin space before.

Neither have I.  I've run into a lot of strange encoding problems working on the matching algorithm.

> I'm guessing that's not an issue that's easy to identify

Yes - what I do is run the compare locally and set breakpoints to find out exactly which characters it trips on.  Not an easy environment to setup, but once it is setup it enables me to zero in on the issues.  I would like to improve the error descriptions, but these types of encoding errors are hard to distinguish from normal miss-matched text.

> would those thin spaces have been removed if I'd copied the original license text, pasted it into, say, notepad++, and copied it from there into my VSCode?

It likely still be an issue since notepad++ retains the encoded characters.  Using notepad++ did make it easier for me to spot the issue since the thin spaces showed up as unprintable characters.

**Comment by johnmhoran** [comment]
@goneall Looks like [the same error](https://travis-ci.com/github/spdx/license-list-XML/jobs/480413235) once again.  Maybe pressing the space bar did not insert a non-thin space?  I'll copy and paste `Technology - Portable` from your .txt into mine and try again.

**Comment by goneall** [comment]
@johnmhoran There 2 occurrences of thin spaces.  It looks like you replaced the first one but not the second one on line 21.

**Comment by johnmhoran** [comment]
@goneall You're right, I did not realize there were 2 occurrences until you pointed it out just now.  Thank you.

**Comment by johnmhoran** [comment]
Excellent.  @goneall I've done a bit of exploring but have not found info re how to set up and run the Travis-like tests locally before I push.  When you have a moment, could you please let me know where I should look?  And thank you for your patience and help on this.  ;-]

**Comment by goneall** [comment]
> I've done a bit of exploring but have not found info re how to set up and run the Travis-like tests locally before I push. 

I just run the [LicenseListPublisher ](https://github.com/spdx/licenselistpublisher) locally.

You can download the current version of LicenseListPublisher from Bintray [here](https://bintray.com/spdx/spdx-tools/download_file?file_path=org%2Fspdx%2FlicenseListPublisher%2F2.1.23%2FlicenseListPublisher-2.1.23-jar-with-dependencies.jar).

The following command will run the same "test" run as part of the CI:

```
LicenseRDFAGenerator licencenseXmlFileOrDir outputDirectory [version] [releasedate] [testfiles] [ignoredwarnings]
   licencenseXmlFileOrDir - a license XML file or a directory of license XML files
   outputDirectory - Directory to store the output from the license generator
   [version] - Version of the SPDX license list
   [releasedate] - Release date of the SPDX license list
   [testfiles] - Directory of original text files to compare the generated licenses against
   [ignoredwarnings] - Either a file name or a comma separated list of warnings to be ignored
```

If you run it against a single XML file, it is MUCH faster than running against the entire repo.

**Comment by johnmhoran** [comment]
Thanks @goneall .

**Comment by jlovejoy** [comment]
seems like this can be merged now?

**Comment by johnmhoran** [comment]
@jlovejoy Yes imho this can be merged now.  I see that you just assigned me, but I do not see a `Merge pull request option` or equivalent -- just `Close with comment` at the bottom, which does not strike me as a merge option.  Please advise.

**Comment by jlovejoy** [comment]
@johnmhoran - I assigned you b/c you made the PR! (gotta make sure you get "credit" ;)

We usually try to have someone who didn't make the PR do the merge as a cross-check. I'll go ahead and merge (look up for the "merge pull request" green button)

Feel free to check and merge any PRs by other people that are otherwise reading to go!

**Comment by johnmhoran** [comment]
Thanks @jlovejoy  -- but looking at other PRs I see no merge button, nor did I see one here -- I don't think I have the necessary access.

**Comment by johnmhoran** [comment]
e.g., for https://github.com/spdx/license-list-XML/pull/1160 I see this:

image

**Pull request merged**
