### PR TITLE
Automated PR for SGI-B-1.0

### PR DESCRIPTION
**Pull request by myndzi**

### CODE REVIEW

**Comment by jlovejoy** [comment]
needs header added and header needs markup (see other version of license for reference)

**Comment by bradleeedmondson** [comment]
can't tackle right now, but will do

**Comment by jlovejoy** [comment]
@bradleeedmondson feel free to assign stuff to me too ;)

**Comment by bradleeedmondson** [comment]
license element fixed up; still needs header added

**Comment by bradleeedmondson** [comment]
added header

**Pull request merged**
