### PR TITLE
LAL-1.3: Minor adjustments, mainly spacing

### PR DESCRIPTION
**Pull request by lkeane**
The formatting of LAL-1.3 in its current form seems to suffer from some odd spacing and line breaks. Maybe this spacing is cleaner?

### CODE REVIEW

**Comment by mlinksva** [comment]
It appears the tests (CI) don't like NNBSP. I'm not sure whether that's a bug in the tests, or if it makes sense to revert 672eef6. Probably others like @goneall will have an opinion or mandate. 😄

**Comment by zvr** [comment]
I would *strongly* suggest we leave spaces as simple ASCII ones.

**Comment by lkeane** [comment]
I just replaced NNBSP with NBSP, and it is now passing checks. NBSP is within Extended ASCII, being character number 255. This xml, LAL's canonical version being French, already uses a number of characters from there such as é (no. 130), à (no. 133), &c. so I am assuming NBSP is acceptable.

**Comment by goneall** [comment]
Agree with @zvr .  It would be a nice enhancement for the compare tools as well.  I submitted [issue #201](https://github.com/spdx/tools/issues/201) on the SPDX tools to track.  Feel free to comment on that issue if you disagree with the change.

**Comment by jlovejoy** [comment]
@goneall @zvr - where does that leave us with this PR then?

**Comment by goneall** [comment]
@jlovejoy The PR is fine as far as I'm concerned.  

I fixed issue 201 on the SPDX tools, so the changes to the spacing will not be necessary in the future.  Keeping the changes in the PR isn't a problem, however.

**Pull request merged**
