### PR TITLE
new license: W3C-20230101

### PR DESCRIPTION
**Pull request by ThisIsMissEm**
Add updated W3C license, the previous versions date from 2015, 2002, and 1998.

I'd also perhaps suggest renaming W3C.xml to W3C-20021231.xml for clarity, though do understand this would be a breaking change. I think I've followed the steps necessary to add a license, so please do let me know if I've missed something, first time contributor.

### CODE REVIEW

**Comment by jlovejoy** [comment]
welcome @ThisIsMissEm - here is a link to the request a new license process https://github.com/spdx/license-list-XML/blob/main/DOCS/request-new-license.md - I don't see a corresponding issue, can you open one, link to this PR, and add some notes as to why this should be added and how it is different from the W3C variants already on the SPDX License List? That would be really helpful for tracking - you don't have to use the SPDX Online Submission tool at this point (unless you want to)

Thanks!

**Comment by xsuchy** [comment]
@ThisIsMissEm can you please open the corresponding issue? Otherwise, I will close this for inactivity.

**Comment by ThisIsMissEm** [comment]
https://github.com/spdx/license-list-XML/issues/2429

**Comment by swinslow** [comment]
#2429 has been resolved with #2447, so I'm closing this one. Thank you @ThisIsMissEm and everyone!

**Pull request closed without merging**
