### PR TITLE
New license: CC-PDDC

### PR DESCRIPTION
**Pull request by jlovejoy**
create new license xml file for CC-PD

### CODE REVIEW

**Comment by jlovejoy** [comment]
this is going to fail b/c I have not made the .txt file yet. But still have questions on short identifier and name - see #836

**Comment by swinslow** [comment]
Based on the comment at https://github.com/spdx/license-list-XML/issues/836#issuecomment-505228524 it looks like ID can be "CC-PDDC" and name can be "Creative Commons Public Domain Dedication and Certification"

**Comment by jlovejoy** [comment]
@bradleeedmondson  or @swinslow  - assuming this passes checks, can one of you review/check and merge?

**Comment by swinslow** [comment]
I think the check is failing because in the XML file the text starts with "THIS WORK IS IN PUBLIC DOMAIN:" (line 12), but in the test file it starts with "Creative Commons Public Domain Dedication and Certification". I can look at addressing this tomorrow (in mtgs all day today), this should be easy for us to take care of. Thanks @jlovejoy!

**Comment by jlovejoy** [comment]
> I think the check is failing because in the XML file the text starts with "THIS WORK IS IN PUBLIC DOMAIN:" (line 12), but in the test file it starts with "Creative Commons Public Domain Dedication and Certification". I can look at addressing this tomorrow (in mtgs all day today), this should be easy for us to take care of. Thanks @jlovejoy!

good catch - not even sure where line 12 came from, as it's not in the original license, so have removed (it also got tagged as the standard license header - gotta watch for weird things being inserted there!)

**Comment by jlovejoy** [comment]
argh, still failing tests!

**Comment by swinslow** [comment]
I think it's because the title in line 1 of the test file ("Creative Commons Public Domain Dedication and Certification") is absent from the XML file... I'd say either remove it from the test file or add it to the XML file and hopefully either would take care of it.

**Comment by swinslow** [comment]
🎉 

@jlovejoy looks good to me, want me to merge?

**Comment by jlovejoy** [comment]
yes please!

**Pull request merged**
