### PR TITLE
Add 'Verbatim-man-pages' license

### PR DESCRIPTION
**Pull request by alejandro-colomar**
Fixes https://github.com/spdx/license-list-XML/issues/1310

@jlovejoy 
@seabass-labrax 
@swinslow

### CODE REVIEW

**Comment by alejandro-colomar** [comment]
BTW, I removed the incorrect punctuation found in the license website, as discussed in the linked issue.

**Comment by seabass-labrax** [comment]
Thank you for this pull request, @alejandro-colomar! The tests pass locally on my machine :)

Please could you add the `listVersionAdded="3.15"` attribute to the `<license>` tag?

Also, I forgot to mention that we'd need to include markup for the erroneous punctuation. This is because users of LTS distributions might have older versions of the man pages for years to come, and should be able to use SPDX-based license scanning tools to produce their bill of materials. Sorry for not mentioning this earlier! The matching syntax is a little weird ([here's an example](https://github.com/spdx/license-list-XML/raw/master/src/exceptions/GCC-exception-2.0.xml)), so if you'd prefer, we can merge this now and I'll add the matching expressions for the 3.15 release.

**Comment by alejandro-colomar** [comment]
re: `listVersionAdded`:  Sure, I was about to do it and I forgot to ask you the version, and then forgot it completely... Done :)

re: punctuation:  I'll try.

**Comment by alejandro-colomar** [comment]
re: punctuation:  I give up!  I cant make sense of it :p

**Review by seabass-labrax — APPROVED** [review]

**Comment by alejandro-colomar** [comment]
I just noticed that the indentation is quite wrong!  BTW, I copied it from BSD-2-clause-simplified (IIRC).
I fixed it to a consistent one, but before uploading, please tell me a few things on how you prefer it:

- amend or another commit?
- Any preferred indentation?  tabs?  spaces? how many?

**Comment by goneall** [comment]
> BTW, I don't know if the groff/man comment syntax is recognized by SPDX tools... And also, there's some wrapper text around the license text in man-pages; you should definitely have a look at it, because it may make SPDX tools go crazy :)

I just looked at the license matching code and the comment syntax isn't recognized.  The comment pattern in implemented in [this line in the Spdx-Java-Library](https://github.com/spdx/Spdx-Java-Library/blob/e47801caeabb3148f75975279ba38ccd63260958/src/main/java/org/spdx/utility/compare/LicenseCompareHelper.java#L138).

**Comment by goneall** [comment]
> Any preferred indentation? tabs? spaces? how many?

Spaces would be preferred - no preferences on the number of spaces.

> amend or another commit?

Flexible - but would prefer another commit.

**Review by swinslow — APPROVED** [review]

**Pull request merged**
