### PR TITLE
Update LGPL-2.1-only.xml

### PR DESCRIPTION
**Pull request by emmanueltournier**
@swinslow  Fixing Issue "Two versions of LGPL-2.1 #1057"  - 
Added alternate language "a brief idea" | "an idea"

### CODE REVIEW

**Comment by swinslow** [comment]
Hi @emmanueltournier, thanks for this! I made a couple of tweaks, and wanted to note here why.

For the `match` property, I changed it to read `match="an idea|a brief idea"`. The `match` property is the one that specifies the regular expression for the different options that can apply. The pipe `|` character between the two options signals that either one is a correct match.

For the `name` property, I admit that I am not entirely sure how this is used in practice, but I believe it can enable tools that are applying the templates to be able to refer to and extract the exact text that was matched against for this field. So I usually see these given unique names if there are multiple `alt` matches within a document.

One other thing -- after the tests pass, we'll want to make the same edit to [`LGPL-2.1-or-later.xml`](https://github.com/spdx/license-list-XML/blob/master/src/LGPL-2.1-or-later.xml), [`LGPL-2.1.xml`](https://github.com/spdx/license-list-XML/blob/master/src/LGPL-2.1.xml) and [`LGPL-2.1+.xml`](https://github.com/spdx/license-list-XML/blob/master/src/LGPL-2.1%2B.xml). For historical reasons, the GPL family of licenses include many different entries on the list. If you get a chance to make this same edit in these files, that's great; if not, I'll make the change before the 3.11 release goes out. Thanks!

**Comment by emmanueltournier** [comment]
Thanks @swinslow . I was also quite confused by the "name" property becasue in this case it is not used. It looks like your modification passed the checks so I'll go ahead with the other LGPL-2.1 licenses.

**Comment by swinslow** [comment]
Thanks @emmanueltournier! If you get a chance to add the others today, that's great; otherwise I will plan to add it myself tomorrow morning before I push the 3.11 release.

**Comment by swinslow** [comment]
Hi @emmanueltournier, I see now that `LGPL-2.1-or-later` and `LGPL-2.1+` weirdly have different markup for that line, which already handles the alt match (in fact it matches against anything at all in that line).

I don't recall why it is different from LGPL-2.1-only, but I'm not going to change it now  :)  So I'll just submit a separate PR for LGPL-2.1 to mirror what you did for LGPL-2.1-only. Thanks again!

**Comment by emmanueltournier** [comment]
Thanks @swinslow ! Sorry, I thought I would have had the time to fix the other licenses yesterday.

**Pull request merged**
