### PR TITLE
Add NCBI-PD

### PR DESCRIPTION
**Pull request by Pandapip1**
Closes https://github.com/spdx/license-list-XML/issues/2419

### CODE REVIEW

**Comment by Pandapip1** [comment]
> First please wait till the issue is approved.

Moving PR to draft.

**Comment by Pandapip1** [comment]
Requesting @swinslow for review and re-labeling

**Comment by Pandapip1** [comment]
(I found a few more variations of the text, ergo the commits)

**Comment by jlovejoy** [comment]
@swinslow - can you review? I think some of the markup we usually do a bit differently

**Comment by Pandapip1** [comment]
I can't figure out why it's failing. Any tips?

**Comment by xsuchy** [comment]
> Normal text of license does not match starting at line #1 column #5 "software" when comparing to template text "PUBLIC DOMAIN NOTICE

You are missing the tile text in the test file.

**Comment by Pandapip1** [comment]
Added the title; it's still failing with what appears to be the same error. If you'd like to take over this PR, I'd totally understand. Otherwise, got any ideas as to why it's failing? Everything seems to be correct, but for some reason the regexes aren't matching correctly.

**Comment by jlovejoy** [comment]
I'm having a go at updating this in small increments. Also adding some line breaks to make it easier to "see" what is going on.

**Comment by jlovejoy** [comment]
ok, so there were a bunch of optional tags that shouldn't be there. Also, I don't see any variation in the [Github search](https://github.com/search?q=%22PUBLIC+DOMAIN+NOTICE%22+%22National+Center+for+Biotechnology+Information%22&type=code&p=1) that @swinslow did that has "created" instead of "written" - we only add markup for variations actually found (and sparingly). But if I missed something, let me know!

Also, given that all of these have the same name in them (National Center for Biotechnology Information / NLM) - I'd be inclined to not mark that up at this point.

We can always add markup if we find variations later

**Comment by jlovejoy** [comment]
ok, last item to consider: the FAQ added at the end as optional - I only see this in one instance. I'd be inclined to just leave it out. It's not part of the license in any case and I think scanning tools can sort this one out

**Review by xsuchy — APPROVED** [review]
Technically speaking the alt matches can be simplified, but this way it is more readable. So +1 from me.

**Review by swinslow — APPROVED** [review]
LGTM; if needed, we can tweak the markup again to add additional variations for future releases. Thank you all!

**Pull request merged**
