### PR TITLE
updates to MPL-2.0-nocopyleft-exception-

### PR DESCRIPTION
**Pull request by jlovejoy**
update Notes re: Exhibit B to make more sense

add standardLicenseHeader tag to Exhibit A and B (it was missing entirely)

### CODE REVIEW

**Comment by jlovejoy** [comment]
@goneall or @zvr or @swinslow - I'm not sure I did the standardLicenseHeader right - there are two bits to be included (text in ExhibitA and text in ExhibitB) - if I use two sets of standardLicenseHeader will it put that text together in the field? Or should I create one standardLicenseHeader tag with it together, outside from the exhibits?

**Comment by goneall** [comment]
@jlovejoy I think we only support 1 standardLicenseHeader, but it looks like it passed verification which surprises me.  I need to verify my understanding.  I'll look into it and add a comment this afternoon.

**Comment by goneall** [comment]
@jlovejoy I just checked and it looks like the different standardLicenseHeaders all get concatenated into a single standardLicenseHeader.  So, this should be fine.

Here's the resulting text.  I noticed a possible issue where an extra linefeed is added between the 2 concatenated licenseheaders:

```
This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.


This Source Code Form is "Incompatible With Secondary Licenses", as defined by the Mozilla Public License, v. 2.0.
```

**Comment by jlovejoy** [comment]
Thanks @goneall ! I don't think the extra line is a major issue (and I'm not sure how to fix it) - agree?

**Comment by goneall** [comment]
> I don't think the extra line is a major issue (and I'm not sure how to fix it) - agree?

Agree - I think this should work fine.

**Comment by swinslow** [comment]
LGTM, thanks @jlovejoy and @goneall! Merging now.

**Pull request merged**
