### PR TITLE
Add GStreamer exception to the GPL

### PR DESCRIPTION
**Pull request by hadess**
Closes: #1442

### CODE REVIEW

**Comment by hadess** [comment]
A couple of things:
- I don't know if the "listVersionAdded" value is correct
- If there is a way to add the [original 2005 totem version of the exception](https://github.com/spdx/license-list-XML/issues/1442#issue-1197054035) for it to be "detected", a pointer to a license doing something similar would be great

**Comment by seabass-labrax** [comment]
>* I don't know if the "listVersionAdded" value is correct

Yup, that's right! We're about to make the 3.17 release, which this can be part of.

>* If there is a way to add the [original 2005 totem version of the exception](https://github.com/spdx/license-list-XML/issues/1442#issue-1197054035) for it to be "detected", a pointer to a license doing something similar would be great

I think that's sufficiently different that it would need a different SPDX identifier, but we can add it too (the Inclusion Principles would be satisfied for that as well, in my opinion).

**Comment by hadess** [comment]
> I think that's sufficiently different that it would need a different SPDX identifier, but we can add it too (the Inclusion Principles would be satisfied for that as well, in my opinion). Maybe something like `GPL-GStreamer-exception-old`?

I've added it as a separate commit, and fixed up the XML to be valid.

**Comment by jlovejoy** [comment]
oh, also - @hadess - can you remove the "DEPRECATED" note in the Note field? "deprecated" has specific meaning within the context of SPDX. 

@swinslow @goneall - are we using <obsoletedBys> tag? I'm not familiar with that one!

**Comment by swinslow** [comment]
Thanks @hadess! Looking at the comments in #1442, it looks like there might be an open question on this one, so I'm going to move it forward to 3.18 (since I'm about to push out 3.17 this evening).

That said, after this is merged (which I expect will be early in 3.18), we typically see projects starting to use new IDs in code even prior to the formal release -- so hopefully that shouldn't be a blocker to your projects looking to use the new IDs. Thanks!

**Comment by hadess** [comment]
> Thanks @hadess! Looking at the comments in #1442, it looks like there might be an open question on this one, so I'm going to move it forward to 3.18 (since I'm about to push out 3.17 this evening).

I'm really disappointed that I would get asked this question moments before you do a release and miss out on the release because of that when the issue and pull request were opened for all to see for the past week and a half.

**Comment by jlovejoy** [comment]
I'm sorry, I'll take responsibility on that - should have caught/questioned about the short ids choice on the call. Put a longer comment in #1442 to try and keep (most) of discussion in one place

**Pull request merged**
