### PR TITLE
Automated PR for CECILL-B

### PR DESCRIPTION
**Pull request by myndzi**

### CODE REVIEW

**Comment by zvr** [comment]
English version available in #437

**Comment by goneall** [comment]
@bradleeedmondson @zvr Checking in on the status of the remaining PR's for CECILL.  Are we ready to merge or is more work needed?  I'll convert the licenses to the new XML properties once they are merged.

**Comment by bradleeedmondson** [comment]
Not sure -- I wasn't done, but I haven't reviewed Alexios' PRs to see if
they covered everything left to do. @zvr ?

**Comment by zvr** [comment]
If we can merge #437, all CECILL licenses will be done (and in English).
I was also planning to run everything through a beautifier (but of course I can do that on the new generated XML files as well).

**Comment by goneall** [comment]
Let's go ahead and merge.  @zvr @bradleeedmondson  let me know if you would like me to do the merge and if all CECIL PR's should be merged.  Once it is all merged, I'll run the translation to the new format.

@zvr No need to run any formatting until after the conversion - it will all change with the translation tool which does do some formatting.

**Comment by zvr** [comment]
If we merge #437, we can ignore #41, #42 and #43

**Comment by goneall** [comment]
@zvr Got it.  You can ignore my review comment I just made on #437.  I'm not quite sure if we want to retain the French translations.  We could accept all the pull requests, transform the XML to the new format, then decide if we want to retain both versions.

@bradleeedmondson for #41, #42, #43 PR's - is it in good enough shape that the XML will parse?  If that is the case, I'll go ahead and merge so that the changes are included in the translated version.

**Comment by bradleeedmondson** [comment]
I think as Alexios says, #437 moots #41, #42, and #43. I haven't reviewed his #437 changes but if they parse and he's happy with the list structure, I'd say you can accept #437 and reject the #41 #42 #43.

**Comment by goneall** [comment]
Agree on the suggested merges.  I'll go ahead and merge/reject as suggested by @bradleeedmondson and @zvr later this afternoon.

**Comment by goneall** [comment]
Closing PR - English version #437 supersedes.  See issue #438 which tracks language translations

**Pull request closed without merging**
