### PR TITLE
fix: Commas in MulanPSL-2.0

### PR DESCRIPTION
**Pull request by nschonni**
Consistent full width comma in Chinese sections, and plain comma in English sections

### CODE REVIEW

**Comment by goneall** [comment]
I think the test is failing due to the license compare implemented in the [SPDX tools library](https://github.com/spdx/Spdx-Java-Library) does not normalize the commas for compare.

This can be worked around by changing the text in the [MulanPSL-2.0 test file](https://github.com/spdx/license-list-XML/blob/master/test/simpleTestForGenerator/MulanPSL-2.0.txt) to match the changes in this license XML.

I added[ issue #42](https://github.com/spdx/Spdx-Java-Library/issues/48) to the SPDX library to update the comparison tools to resolve the underlying issue.

**Comment by nschonni** [comment]
@goneall I flipped this to Draft because when I looked at the "source" published license it has these inconsistencies in the comma/space.

**Comment by jlovejoy** [comment]
given that these instances look to occur in the TitleText tag - which is not pertinent for matching purposes, I think we can just close this?
@goneall  - agree?

**Comment by goneall** [comment]
> given that these instances look to occur in the TitleText tag - which is not pertinent for matching purposes, I think we can just close this?

It does impact how the license is displayed (although you have to look very closely to see the difference).

@nschonni what do you think?  For matching purposes, the changes shouldn't have an impact - only the display.

**Comment by jlovejoy** [comment]
I'm going to close this now, since it doesn't make a difference and there hasn't been any activity

**Pull request closed without merging**
