### PR TITLE
Automated PR for HPND

### PR DESCRIPTION
**Pull request by myndzi**

### CODE REVIEW

**Comment by sam-ellis** [comment]
Needs text in square braces [] to be replaced with tags of some sort.

**Comment by sam-ellis** [comment]
Pull request submitted to replace [] with alt and optional tags. These are more complex than usual, so care should be taken when reviewing these.

**Comment by bradleeedmondson** [comment]
structure looks OK, and to my less-than-experienced eye the &lt;alt&gt; and &lt;optional&gt; tags look OK.

Question for the legal team: merge now or should we have someone else review it first?

**Comment by jlovejoy** [comment]
looks good to me. noticed we have some nesting optional tags - is this ok? @myndzi ??

**Pull request merged**
