### PR TITLE
New License: Inner-Net-2.0

### LINKED ISSUE #1987: New license request: Inner-Net-2.0 [SPDX-Online-Tools]
**1.** License Name: Inner Net License v2.0
**2.** Short identifier: Inner-Net-2.0
**3.** License Author or steward: Unknown
**4.** Comments: This is an older license that is approved and used in Fedora. I think it meets the inclusion principles.

See https://gitlab.com/fedora/legal/fedora-license-data/-/issues/16
**5.** License Request Url: http://tools.spdx.org/app/license_requests/236
**6.** URL(s): https://fedoraproject.org/wiki/Licensing/Inner_Net_License
**7.** OSI Status: Unknown
**8.** Example Projects: https://www.gnu.org/software/libc/sources.html

### PR DESCRIPTION
**Pull request by jlovejoy**
Fixes #1987

### CODE REVIEW

**Comment by swinslow** [comment]
revised the intro comment to add "fixes" line so that the linked issue will close  :)

**Comment by swinslow** [comment]
@jlovejoy Here's a maybe dumb question:

The title of the license given in the license text is "The Inner Net License, Version 2.00".
So, should the ID be `Inner-Net-2.00` instead of `Inner-Net-2.0`? And the license title "The Inner Net License, Version 2.00" rather than "Inner Net License v2.0"?

I'm not going to lose sleep over this, so if you want to proceed as-is, it looks otherwise fine to me and I can merge.

**Comment by swinslow** [comment]
@jlovejoy I know you want to get this in for 3.21, so I'll go ahead and merge it with 2.0 rather than 2.00 as the ID.

**Comment by jlovejoy** [comment]
Thanks @swinslow - yeah, I considered the .00 for a second or two but then thought it seemed a bit unnecessary

**Pull request merged**
